# app/api/v1/vendor_variant_management.py
"""
Variant Management — list/inline-edit/bulk-update/delete for variants that
already exist (whether created manually via the product form or generated by
app.services.variant_generator). This is the API behind the Excel-like
Variant Management grid + the Variant Details Drawer.
"""
import math
from uuid import UUID
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import JSONResponse
from sqlalchemy import select, func, or_
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.api.deps import get_current_vendor_id, require_permission
from app.models.vendor_product import ProductVariant
from app.api.v1.vendor_variant_generator import _get_owned_product
from app.schemas.variant_management import (
    VariantListResponse, VariantListItem, VariantPatchRequest,
    BulkUpdateRequest, BulkUpdateResponse, BulkDeleteRequest, BulkDeleteResponse,
    PriceAdjustMode,
)

router = APIRouter(dependencies=[Depends(require_permission("products.view"))])


def _num(v):
    return float(v) if v is not None else None


def _list_item_dict(v: ProductVariant) -> dict:
    return {
        "id": str(v.id),
        "name": v.name,
        "sku": v.sku,
        "barcode": v.barcode,
        "uom": v.uom or "piece",
        "price": _num(v.price) or 0,
        "compare_at_price": _num(v.compare_at_price),
        "cost_price": _num(v.cost_price),
        "currency": v.currency or "INR",
        "is_taxable": v.is_taxable if v.is_taxable is not None else True,
        "tax_rate": _num(v.tax_rate),
        "quantity": v.quantity or 0,
        "low_stock_threshold": v.low_stock_threshold or 5,
        "stock_status": v.stock_status,
        "track_inventory": v.track_inventory if v.track_inventory is not None else True,
        "attributes": v.attributes or {},
        "config_selection": v.config_selection,
        "variant_hash": v.variant_hash,
        "media": v.media or [],
        "color": v.color,
        "is_active": v.is_active if v.is_active is not None else True,
        "created_at": v.created_at.isoformat() if v.created_at else None,
        "updated_at": v.updated_at.isoformat() if v.updated_at else None,
    }


def _detail_dict(v: ProductVariant) -> dict:
    d = _list_item_dict(v)
    d.update({
        "uom_quantity": _num(v.uom_quantity),
        "price_type": v.price_type or "per_unit",
        "discount_percentage": _num(v.discount_percentage),
        "discount_amount": _num(v.discount_amount),
        "offer_label": v.offer_label,
        "is_on_sale": v.is_on_sale or False,
        "hsn_code": v.hsn_code,
        "gst_rate": _num(v.gst_rate),
        "reorder_point": v.reorder_point,
        "reorder_quantity": v.reorder_quantity,
        "allow_backorders": v.allow_backorders or False,
        "max_quantity_per_order": v.max_quantity_per_order,
        "min_quantity_per_order": v.min_quantity_per_order,
        "weight_kg": _num(v.weight_kg),
        "expiration_date": v.expiration_date.isoformat() if v.expiration_date else None,
        "manufacture_date": v.manufacture_date.isoformat() if v.manufacture_date else None,
        "best_before_date": v.best_before_date.isoformat() if v.best_before_date else None,
        "warranty_period_days": v.warranty_period_days,
        "warranty_type": v.warranty_type,
        "is_returnable": v.is_returnable if v.is_returnable is not None else True,
        "return_days": v.return_days,
        "refund_policy": v.refund_policy,
        "return_policy": v.return_policy,
        "return_conditions": v.return_conditions,
        "search_keywords": v.search_keywords,
        "subscription_interval": v.subscription_interval,
        "subscription_trial_days": v.subscription_trial_days,
        "subscription_setup_fee": _num(v.subscription_setup_fee),
        "subscription_billing_cycles": v.subscription_billing_cycles,
    })
    return d


async def _get_owned_variant(db: AsyncSession, vendor_id: UUID, product_id: UUID, variant_id: UUID) -> ProductVariant:
    await _get_owned_product(db, vendor_id, product_id)
    result = await db.execute(
        select(ProductVariant).where(ProductVariant.id == variant_id, ProductVariant.product_id == product_id)
    )
    variant = result.scalar_one_or_none()
    if not variant:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Variant not found")
    return variant


@router.get("/{product_id}/variants", response_model=VariantListResponse)
async def list_variants(
    product_id: UUID,
    page: int = Query(1, ge=1),
    size: int = Query(2000, ge=1, le=10000),
    search: Optional[str] = Query(None),
    is_active: Optional[bool] = Query(None),
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    """Lean, grid-ready list of every variant for a product. Defaults to a
    large page size (2000) since the frontend virtualizes rendering rather
    than paginating through the UI — pass a smaller `size` to paginate anyway."""
    await _get_owned_product(db, vendor_id, product_id)

    stmt = select(ProductVariant).where(ProductVariant.product_id == product_id)
    count_stmt = select(func.count()).select_from(ProductVariant).where(ProductVariant.product_id == product_id)

    if is_active is not None:
        stmt = stmt.where(ProductVariant.is_active == is_active)
        count_stmt = count_stmt.where(ProductVariant.is_active == is_active)
    if search:
        like = f"%{search.lower()}%"
        cond = or_(
            func.lower(ProductVariant.name).like(like),
            func.lower(ProductVariant.sku).like(like),
            func.lower(ProductVariant.barcode).like(like),
            func.lower(ProductVariant.search_keywords).like(like),
        )
        stmt = stmt.where(cond)
        count_stmt = count_stmt.where(cond)

    total = (await db.execute(count_stmt)).scalar() or 0
    stmt = stmt.order_by(ProductVariant.created_at).offset((page - 1) * size).limit(size)
    result = await db.execute(stmt)
    items = list(result.scalars().all())

    return JSONResponse(content=VariantListResponse(
        items=[VariantListItem(**_list_item_dict(v)) for v in items],
        total=total, page=page, size=size,
        pages=math.ceil(total / size) if total > 0 else 0,
    ).model_dump())


@router.get("/{product_id}/variants/{variant_id}")
async def get_variant(
    product_id: UUID, variant_id: UUID,
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    variant = await _get_owned_variant(db, vendor_id, product_id, variant_id)
    return JSONResponse(content=_detail_dict(variant))


@router.patch("/{product_id}/variants/{variant_id}")
async def patch_variant(
    product_id: UUID, variant_id: UUID, data: VariantPatchRequest,
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    """Single-cell (or small multi-field) inline edit from the grid or the
    details drawer — only fields present in the payload are touched."""
    from datetime import date as date_cls

    variant = await _get_owned_variant(db, vendor_id, product_id, variant_id)
    update_data = data.model_dump(exclude_unset=True)
    date_fields = ("manufacture_date", "expiration_date", "best_before_date")
    for field, value in update_data.items():
        if field in date_fields:
            if value in (None, ""):
                setattr(variant, field, None)
            else:
                setattr(variant, field, date_cls.fromisoformat(str(value)[:10]))
        else:
            setattr(variant, field, value)
    await db.commit()
    await db.refresh(variant)
    return JSONResponse(content=_detail_dict(variant))


@router.delete("/{product_id}/variants/{variant_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_variant(
    product_id: UUID, variant_id: UUID,
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    variant = await _get_owned_variant(db, vendor_id, product_id, variant_id)
    await db.delete(variant)
    await db.commit()


def _apply_price_adjustment(variant: ProductVariant, adj) -> None:
    current = getattr(variant, adj.field, None)
    current = float(current) if current is not None else 0.0
    if adj.mode == PriceAdjustMode.SET:
        new_value = adj.value
    elif adj.mode == PriceAdjustMode.INCREASE_PCT:
        new_value = current * (1 + adj.value / 100)
    elif adj.mode == PriceAdjustMode.DECREASE_PCT:
        new_value = current * (1 - adj.value / 100)
    elif adj.mode == PriceAdjustMode.INCREASE_AMT:
        new_value = current + adj.value
    elif adj.mode == PriceAdjustMode.DECREASE_AMT:
        new_value = current - adj.value
    else:
        return
    setattr(variant, adj.field, max(0.0, round(new_value, 2)))


@router.post("/{product_id}/variants/bulk-update", response_model=BulkUpdateResponse)
async def bulk_update_variants(
    product_id: UUID, data: BulkUpdateRequest,
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    await _get_owned_product(db, vendor_id, product_id)
    try:
        variant_ids = [UUID(v) for v in data.variant_ids]
    except ValueError:
        raise HTTPException(400, "Invalid variant id in variant_ids")

    result = await db.execute(
        select(ProductVariant).where(ProductVariant.product_id == product_id, ProductVariant.id.in_(variant_ids))
    )
    variants = list(result.scalars().all())

    set_fields = data.set_fields.model_dump(exclude_unset=True) if data.set_fields else {}
    for v in variants:
        for field, value in set_fields.items():
            setattr(v, field, value)
        if data.price_adjustment:
            _apply_price_adjustment(v, data.price_adjustment)

    await db.commit()
    return JSONResponse(content=BulkUpdateResponse(updated_count=len(variants)).model_dump())


@router.post("/{product_id}/variants/bulk-delete", response_model=BulkDeleteResponse)
async def bulk_delete_variants(
    product_id: UUID, data: BulkDeleteRequest,
    vendor_id: UUID = Depends(get_current_vendor_id),
    db: AsyncSession = Depends(get_db),
):
    await _get_owned_product(db, vendor_id, product_id)
    try:
        variant_ids = [UUID(v) for v in data.variant_ids]
    except ValueError:
        raise HTTPException(400, "Invalid variant id in variant_ids")

    result = await db.execute(
        select(ProductVariant).where(ProductVariant.product_id == product_id, ProductVariant.id.in_(variant_ids))
    )
    variants = list(result.scalars().all())
    for v in variants:
        await db.delete(v)
    await db.commit()
    return JSONResponse(content=BulkDeleteResponse(deleted_count=len(variants)).model_dump())
