import type { ElementType } from 'react'
import {
  Eye, Package, Wrench, ShoppingCart, Calendar, Receipt, FileText, FilePlus, Tag,
  RefreshCw, Truck, Factory, Users as UsersIcon, MessageSquare, Settings, UserPlus,
  ShieldCheck, UserCog, Target, Landmark, Percent, UtensilsCrossed, Warehouse,
  ClipboardList, BarChart3, Globe, Store, Heart,
} from 'lucide-react'

/** Human-readable labels for permission module keys (prefix before the first dot). */
export const PERMISSION_MODULE_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  products: 'Products',
  services: 'Services',
  orders: 'Orders',
  bookings: 'Bookings',
  pos: 'Point of Sale',
  invoices: 'Invoices & Billing',
  memos: 'Credit / Debit Memos',
  coupons: 'Coupons & Promos',
  subscriptions: 'Subscriptions',
  rentals: 'Rentals',
  production: 'Production Orders',
  customers: 'Customers',
  reviews: 'Reviews',
  inventory: 'Inventory',
  procurement: 'Purchase Orders',
  merchandising: 'Merchandising',
  loyalty: 'Loyalty',
  restaurant: 'Restaurant',
  commission: 'Commission',
  reports: 'Reports',
  websites: 'Website Builder',
  settings: 'Settings',
  team: 'Staff Access Control',
  roles: 'Roles',
  hr: 'Human Resources',
  crm: 'CRM',
  finance: 'Finance',
}

export const PERMISSION_MODULE_ICONS: Record<string, ElementType> = {
  dashboard: Eye,
  products: Package,
  services: Wrench,
  orders: ShoppingCart,
  bookings: Calendar,
  pos: Receipt,
  invoices: FileText,
  memos: FilePlus,
  coupons: Tag,
  subscriptions: RefreshCw,
  rentals: Truck,
  production: Factory,
  customers: UsersIcon,
  reviews: MessageSquare,
  inventory: Warehouse,
  procurement: ClipboardList,
  merchandising: Store,
  loyalty: Heart,
  restaurant: UtensilsCrossed,
  commission: Percent,
  reports: BarChart3,
  websites: Globe,
  settings: Settings,
  team: UserPlus,
  roles: ShieldCheck,
  hr: UserCog,
  crm: Target,
  finance: Landmark,
}
