/** Shared unit-of-measure options for products, services, and variants. */

export type UomOption = { value: string; label: string; group: string }

export const UOM_OPTIONS: UomOption[] = [
  // Count
  { value: 'piece', label: 'Piece (pc)', group: 'Count' },
  { value: 'unit', label: 'Unit', group: 'Count' },
  { value: 'pair', label: 'Pair', group: 'Count' },
  { value: 'dozen', label: 'Dozen (12)', group: 'Count' },
  { value: 'gross', label: 'Gross (144)', group: 'Count' },
  { value: 'set', label: 'Set', group: 'Count' },
  { value: 'kit', label: 'Kit', group: 'Count' },
  { value: 'pack', label: 'Pack', group: 'Count' },
  { value: 'bundle', label: 'Bundle', group: 'Count' },
  { value: 'box', label: 'Box', group: 'Count' },
  { value: 'case', label: 'Case', group: 'Count' },
  { value: 'carton', label: 'Carton', group: 'Count' },
  { value: 'pallet', label: 'Pallet', group: 'Count' },
  { value: 'roll', label: 'Roll', group: 'Count' },
  { value: 'reel', label: 'Reel', group: 'Count' },
  { value: 'sheet', label: 'Sheet', group: 'Count' },
  { value: 'bag', label: 'Bag', group: 'Count' },
  { value: 'bottle', label: 'Bottle', group: 'Count' },
  { value: 'can', label: 'Can', group: 'Count' },
  { value: 'jar', label: 'Jar', group: 'Count' },
  { value: 'tube', label: 'Tube', group: 'Count' },
  { value: 'sachet', label: 'Sachet', group: 'Count' },
  { value: 'pouch', label: 'Pouch', group: 'Count' },
  { value: 'spool', label: 'Spool', group: 'Count' },
  { value: 'coil', label: 'Coil', group: 'Count' },
  { value: 'drum', label: 'Drum', group: 'Count' },
  { value: 'canister', label: 'Canister', group: 'Count' },
  { value: 'bin', label: 'Bin', group: 'Count' },
  { value: 'lot', label: 'Lot', group: 'Count' },
  { value: 'ream', label: 'Ream (500 sheets)', group: 'Count' },
  { value: 'quire', label: 'Quire (25 sheets)', group: 'Count' },
  { value: 'skid', label: 'Skid', group: 'Count' },
  { value: 'container_load', label: 'Container Load', group: 'Count' },
  { value: 'truckload', label: 'Truckload', group: 'Count' },
  { value: 'assortment', label: 'Assortment', group: 'Count' },
  { value: 'sample', label: 'Sample', group: 'Count' },
  // Weight
  { value: 'mcg', label: 'Microgram (µg)', group: 'Weight' },
  { value: 'mg', label: 'Milligram (mg)', group: 'Weight' },
  { value: 'g', label: 'Gram (g)', group: 'Weight' },
  { value: 'kg', label: 'Kilogram (kg)', group: 'Weight' },
  { value: 'tonne', label: 'Metric Ton (t)', group: 'Weight' },
  { value: 'short_ton', label: 'Short Ton (US)', group: 'Weight' },
  { value: 'long_ton', label: 'Long Ton (UK)', group: 'Weight' },
  { value: 'oz', label: 'Ounce (oz)', group: 'Weight' },
  { value: 'troy_oz', label: 'Troy Ounce (ozt)', group: 'Weight' },
  { value: 'lb', label: 'Pound (lb)', group: 'Weight' },
  { value: 'stone', label: 'Stone (st)', group: 'Weight' },
  { value: 'quintal', label: 'Quintal (100 kg)', group: 'Weight' },
  { value: 'carat', label: 'Carat (ct, 0.2 g)', group: 'Weight' },
  { value: 'tola', label: 'Tola (11.66 g)', group: 'Weight' },
  { value: 'grain', label: 'Grain (gr)', group: 'Weight' },
  { value: 'pennyweight', label: 'Pennyweight (dwt)', group: 'Weight' },
  // Volume
  { value: 'mcl', label: 'Microlitre (µL)', group: 'Volume' },
  { value: 'ml', label: 'Millilitre (ml)', group: 'Volume' },
  { value: 'cl', label: 'Centilitre (cl)', group: 'Volume' },
  { value: 'dl', label: 'Decilitre (dl)', group: 'Volume' },
  { value: 'l', label: 'Litre (L)', group: 'Volume' },
  { value: 'kl', label: 'Kilolitre (kL)', group: 'Volume' },
  { value: 'cubic_cm', label: 'Cubic Centimetre (cc)', group: 'Volume' },
  { value: 'cubic_m', label: 'Cubic Metre (m³)', group: 'Volume' },
  { value: 'cubic_ft', label: 'Cubic Foot (ft³)', group: 'Volume' },
  { value: 'cubic_yard', label: 'Cubic Yard (yd³)', group: 'Volume' },
  { value: 'cubic_in', label: 'Cubic Inch (in³)', group: 'Volume' },
  { value: 'barrel', label: 'Barrel (bbl)', group: 'Volume' },
  { value: 'bushel_vol', label: 'Bushel (vol, 36.4 L)', group: 'Volume' },
  { value: 'fl_oz', label: 'Fluid Ounce (fl oz)', group: 'Volume' },
  { value: 'pt', label: 'Pint (pt)', group: 'Volume' },
  { value: 'qt', label: 'Quart (qt)', group: 'Volume' },
  { value: 'gal', label: 'Gallon (gal)', group: 'Volume' },
  { value: 'cup', label: 'Cup', group: 'Volume' },
  { value: 'tbsp', label: 'Tablespoon (tbsp)', group: 'Volume' },
  { value: 'tsp', label: 'Teaspoon (tsp)', group: 'Volume' },
  // Length
  { value: 'nm', label: 'Nanometre (nm)', group: 'Length' },
  { value: 'micron', label: 'Micron (µm)', group: 'Length' },
  { value: 'mm', label: 'Millimetre (mm)', group: 'Length' },
  { value: 'cm', label: 'Centimetre (cm)', group: 'Length' },
  { value: 'm', label: 'Metre (m)', group: 'Length' },
  { value: 'km', label: 'Kilometre (km)', group: 'Length' },
  { value: 'in', label: 'Inch (in)', group: 'Length' },
  { value: 'ft', label: 'Foot (ft)', group: 'Length' },
  { value: 'yd', label: 'Yard (yd)', group: 'Length' },
  { value: 'mile', label: 'Mile (mi)', group: 'Length' },
  { value: 'nautical_mile', label: 'Nautical Mile (nmi)', group: 'Length' },
  { value: 'running_meter', label: 'Running Metre (RM)', group: 'Length' },
  { value: 'linear_foot', label: 'Linear Foot (LF)', group: 'Length' },
  { value: 'board_foot', label: 'Board Foot (bf)', group: 'Length' },
  { value: 'chain', label: 'Chain (22 yd)', group: 'Length' },
  { value: 'furlong', label: 'Furlong', group: 'Length' },
  { value: 'fathom', label: 'Fathom (6 ft)', group: 'Length' },
  // Area
  { value: 'sq_mm', label: 'Square Millimetre (mm²)', group: 'Area' },
  { value: 'sq_cm', label: 'Square Centimetre (cm²)', group: 'Area' },
  { value: 'sq_m', label: 'Square Metre (m²)', group: 'Area' },
  { value: 'sq_km', label: 'Square Kilometre (km²)', group: 'Area' },
  { value: 'sq_in', label: 'Square Inch (in²)', group: 'Area' },
  { value: 'sq_ft', label: 'Square Foot (ft²)', group: 'Area' },
  { value: 'sq_yd', label: 'Square Yard (yd²)', group: 'Area' },
  { value: 'acre', label: 'Acre', group: 'Area' },
  { value: 'hectare', label: 'Hectare (ha)', group: 'Area' },
  { value: 'marla', label: 'Marla', group: 'Area' },
  { value: 'kanal', label: 'Kanal', group: 'Area' },
  { value: 'sq_mile', label: 'Square Mile (mi²)', group: 'Area' },
  { value: 'sq_chain', label: 'Square Chain', group: 'Area' },
  // Agriculture — land, produce, inputs, livestock
  { value: 'bigha', label: 'Bigha', group: 'Agriculture' },
  { value: 'guntha', label: 'Guntha / Gunta', group: 'Agriculture' },
  { value: 'cent', label: 'Cent (1/100 Acre)', group: 'Agriculture' },
  { value: 'per_acre', label: 'Per Acre', group: 'Agriculture' },
  { value: 'per_hectare', label: 'Per Hectare', group: 'Agriculture' },
  { value: 'per_bigha', label: 'Per Bigha', group: 'Agriculture' },
  { value: 'bushel', label: 'Bushel', group: 'Agriculture' },
  { value: 'maund', label: 'Maund', group: 'Agriculture' },
  { value: 'cwt', label: 'Hundredweight (cwt)', group: 'Agriculture' },
  { value: 'gunny_bag', label: 'Gunny Bag / Sack', group: 'Agriculture' },
  { value: 'sack', label: 'Sack', group: 'Agriculture' },
  { value: 'bale', label: 'Bale', group: 'Agriculture' },
  { value: 'crate', label: 'Crate', group: 'Agriculture' },
  { value: 'tray', label: 'Tray', group: 'Agriculture' },
  { value: 'punnet', label: 'Punnet', group: 'Agriculture' },
  { value: 'katta', label: 'Katta (Cane Bundle)', group: 'Agriculture' },
  { value: 'plant', label: 'Plant', group: 'Agriculture' },
  { value: 'sapling', label: 'Sapling', group: 'Agriculture' },
  { value: 'tree', label: 'Tree', group: 'Agriculture' },
  { value: 'seedling', label: 'Seedling', group: 'Agriculture' },
  { value: 'cutting', label: 'Cutting', group: 'Agriculture' },
  { value: 'bulb', label: 'Bulb', group: 'Agriculture' },
  { value: 'tuber', label: 'Tuber', group: 'Agriculture' },
  { value: 'per_plant', label: 'Per Plant', group: 'Agriculture' },
  { value: 'per_tree', label: 'Per Tree', group: 'Agriculture' },
  { value: 'head', label: 'Head (Livestock)', group: 'Agriculture' },
  { value: 'flock', label: 'Flock', group: 'Agriculture' },
  { value: 'herd', label: 'Herd', group: 'Agriculture' },
  { value: 'dose', label: 'Dose (Veterinary)', group: 'Agriculture' },
  { value: 'litre_per_acre', label: 'Litre per Acre', group: 'Agriculture' },
  { value: 'kg_per_acre', label: 'Kg per Acre', group: 'Agriculture' },
  // Time
  { value: 'second', label: 'Second (sec)', group: 'Time' },
  { value: 'minute', label: 'Minute (min)', group: 'Time' },
  { value: 'hour', label: 'Hour (hr)', group: 'Time' },
  { value: 'half_day', label: 'Half Day', group: 'Time' },
  { value: 'day', label: 'Day', group: 'Time' },
  { value: 'fortnight', label: 'Fortnight (2 weeks)', group: 'Time' },
  { value: 'week', label: 'Week', group: 'Time' },
  { value: 'month', label: 'Month', group: 'Time' },
  { value: 'quarter', label: 'Quarter (3 months)', group: 'Time' },
  { value: 'half_year', label: 'Half Year (6 months)', group: 'Time' },
  { value: 'year', label: 'Year', group: 'Time' },
  { value: 'shift', label: 'Shift', group: 'Time' },
  { value: 'man_day', label: 'Man Day (MD)', group: 'Time' },
  { value: 'man_hour', label: 'Man Hour (MH)', group: 'Time' },
  { value: 'session', label: 'Session', group: 'Time' },
  { value: 'per_session', label: 'Per Session', group: 'Time' },
  { value: 'per_minute', label: 'Per Minute', group: 'Time' },
  { value: 'per_hour', label: 'Per Hour', group: 'Time' },
  { value: 'per_day', label: 'Per Day', group: 'Time' },
  { value: 'per_week', label: 'Per Week', group: 'Time' },
  { value: 'per_month', label: 'Per Month', group: 'Time' },
  { value: 'per_year', label: 'Per Year', group: 'Time' },
  // Service
  { value: 'visit', label: 'Visit', group: 'Service' },
  { value: 'appointment', label: 'Appointment', group: 'Service' },
  { value: 'consultation', label: 'Consultation', group: 'Service' },
  { value: 'treatment', label: 'Treatment', group: 'Service' },
  { value: 'call', label: 'Call', group: 'Service' },
  { value: 'job', label: 'Job', group: 'Service' },
  { value: 'project', label: 'Project', group: 'Service' },
  { value: 'task', label: 'Task', group: 'Service' },
  { value: 'ticket', label: 'Ticket', group: 'Service' },
  { value: 'class', label: 'Class', group: 'Service' },
  { value: 'lesson', label: 'Lesson', group: 'Service' },
  { value: 'workshop', label: 'Workshop', group: 'Service' },
  { value: 'event', label: 'Event', group: 'Service' },
  { value: 'trip', label: 'Trip', group: 'Service' },
  { value: 'tour', label: 'Tour', group: 'Service' },
  { value: 'ride', label: 'Ride', group: 'Service' },
  { value: 'delivery', label: 'Delivery', group: 'Service' },
  { value: 'installation', label: 'Installation', group: 'Service' },
  { value: 'inspection', label: 'Inspection', group: 'Service' },
  { value: 'subscription', label: 'Subscription', group: 'Service' },
  { value: 'contract', label: 'Contract', group: 'Service' },
  { value: 'retainer', label: 'Retainer', group: 'Service' },
  { value: 'milestone', label: 'Milestone', group: 'Service' },
  { value: 'phase', label: 'Phase', group: 'Service' },
  { value: 'sprint', label: 'Sprint', group: 'Service' },
  { value: 'revision', label: 'Revision', group: 'Service' },
  { value: 'report', label: 'Report', group: 'Service' },
  { value: 'audit', label: 'Audit', group: 'Service' },
  { value: 'manpower', label: 'Manpower (head count)', group: 'Service' },
  { value: 'crew', label: 'Crew', group: 'Service' },
  // Textile / Fabric
  { value: 'running_meter_fab', label: 'Running Metre (fabric)', group: 'Textile' },
  { value: 'linear_meter_fab', label: 'Linear Metre', group: 'Textile' },
  { value: 'yard_fab', label: 'Yard (fabric)', group: 'Textile' },
  { value: 'gsm', label: 'GSM (g/m²)', group: 'Textile' },
  { value: 'denier', label: 'Denier (D)', group: 'Textile' },
  { value: 'tex', label: 'Tex', group: 'Textile' },
  { value: 'thread_count', label: 'Thread Count (TC)', group: 'Textile' },
  { value: 'cone', label: 'Cone (yarn)', group: 'Textile' },
  { value: 'hank', label: 'Hank', group: 'Textile' },
  { value: 'skein', label: 'Skein', group: 'Textile' },
  { value: 'bolt', label: 'Bolt (fabric roll)', group: 'Textile' },
  { value: 'garment', label: 'Garment', group: 'Textile' },
  { value: 'article', label: 'Article', group: 'Textile' },
  // Logistics / Shipping
  { value: 'teu', label: 'TEU (20-ft container)', group: 'Logistics' },
  { value: 'feu', label: 'FEU (40-ft container)', group: 'Logistics' },
  { value: 'cbm', label: 'CBM (Cubic Metre)', group: 'Logistics' },
  { value: 'shipment', label: 'Shipment', group: 'Logistics' },
  { value: 'consignment', label: 'Consignment', group: 'Logistics' },
  { value: 'load', label: 'Load', group: 'Logistics' },
  { value: 'ltl', label: 'LTL (Less-than-Truckload)', group: 'Logistics' },
  { value: 'ftl', label: 'FTL (Full Truckload)', group: 'Logistics' },
  { value: 'fcl', label: 'FCL (Full Container Load)', group: 'Logistics' },
  { value: 'lcl', label: 'LCL (Less-than-Container Load)', group: 'Logistics' },
  { value: 'parcel', label: 'Parcel', group: 'Logistics' },
  { value: 'package', label: 'Package', group: 'Logistics' },
  { value: 'pallet_slot', label: 'Pallet Slot', group: 'Logistics' },
  // Construction
  { value: 'cubic_yard_c', label: 'Cubic Yard (conc.)', group: 'Construction' },
  { value: 'bag_cement', label: 'Bag of Cement (50 kg)', group: 'Construction' },
  { value: 'brick_unit', label: 'Brick', group: 'Construction' },
  { value: 'block_unit', label: 'Block / CMU', group: 'Construction' },
  { value: 'sq_ft_built', label: 'Sq Ft (built-up)', group: 'Construction' },
  { value: 'sq_m_built', label: 'Sq Metre (built-up)', group: 'Construction' },
  { value: 'running_ft_c', label: 'Running Foot', group: 'Construction' },
  { value: 'rft', label: 'RFT (Running Foot)', group: 'Construction' },
  { value: 'point', label: 'Point (1/12 inch)', group: 'Construction' },
  // Hospitality / Hotel
  { value: 'room', label: 'Room', group: 'Hospitality' },
  { value: 'room_night', label: 'Room-Night', group: 'Hospitality' },
  { value: 'night', label: 'Night', group: 'Hospitality' },
  { value: 'stay', label: 'Stay', group: 'Hospitality' },
  { value: 'guest', label: 'Guest', group: 'Hospitality' },
  { value: 'guest_night', label: 'Guest-Night', group: 'Hospitality' },
  { value: 'person', label: 'Person / Pax', group: 'Hospitality' },
  { value: 'person_night', label: 'Person-Night', group: 'Hospitality' },
  { value: 'bed', label: 'Bed', group: 'Hospitality' },
  { value: 'suite', label: 'Suite', group: 'Hospitality' },
  { value: 'cottage', label: 'Cottage / Cabin', group: 'Hospitality' },
  { value: 'villa', label: 'Villa', group: 'Hospitality' },
  { value: 'booking', label: 'Booking', group: 'Hospitality' },
  { value: 'check_in', label: 'Check-in', group: 'Hospitality' },
  { value: 'tent', label: 'Tent / Pitch', group: 'Hospitality' },
  { value: 'dormitory_bed', label: 'Dormitory Bed', group: 'Hospitality' },
  // Restaurant / F&B
  { value: 'plate', label: 'Plate', group: 'Restaurant' },
  { value: 'dish', label: 'Dish', group: 'Restaurant' },
  { value: 'serving', label: 'Serving', group: 'Restaurant' },
  { value: 'portion', label: 'Portion', group: 'Restaurant' },
  { value: 'half_portion', label: 'Half Portion', group: 'Restaurant' },
  { value: 'full_portion', label: 'Full Portion', group: 'Restaurant' },
  { value: 'cover', label: 'Cover (Guest)', group: 'Restaurant' },
  { value: 'per_head', label: 'Per Head', group: 'Restaurant' },
  { value: 'table', label: 'Table', group: 'Restaurant' },
  { value: 'order', label: 'Order', group: 'Restaurant' },
  { value: 'meal', label: 'Meal', group: 'Restaurant' },
  { value: 'combo', label: 'Combo / Meal Deal', group: 'Restaurant' },
  { value: 'thali', label: 'Thali', group: 'Restaurant' },
  { value: 'platter', label: 'Platter', group: 'Restaurant' },
  { value: 'bowl', label: 'Bowl', group: 'Restaurant' },
  { value: 'glass', label: 'Glass', group: 'Restaurant' },
  { value: 'slice', label: 'Slice', group: 'Restaurant' },
  { value: 'scoop', label: 'Scoop', group: 'Restaurant' },
  { value: 'stick', label: 'Stick / Skewer', group: 'Restaurant' },
  { value: 'buffet', label: 'Buffet', group: 'Restaurant' },
  { value: 'takeaway', label: 'Takeaway / Parcel', group: 'Restaurant' },
  { value: 'add_on', label: 'Add-on', group: 'Restaurant' },
  { value: 'course', label: 'Course', group: 'Restaurant' },
  { value: 'tasting_menu', label: 'Tasting Menu', group: 'Restaurant' },
  { value: 'flight', label: 'Flight (Drinks)', group: 'Restaurant' },
  { value: 'jug', label: 'Jug', group: 'Restaurant' },
  { value: 'shot', label: 'Shot', group: 'Restaurant' },
  // Restaurant sizes (S/M/L, drink sizes, sharing)
  { value: 'size_xs', label: 'Extra Small', group: 'Restaurant Size' },
  { value: 'size_sm', label: 'Small', group: 'Restaurant Size' },
  { value: 'size_md', label: 'Medium / Regular', group: 'Restaurant Size' },
  { value: 'size_lg', label: 'Large', group: 'Restaurant Size' },
  { value: 'size_xl', label: 'Extra Large', group: 'Restaurant Size' },
  { value: 'size_xxl', label: 'XXL / Jumbo', group: 'Restaurant Size' },
  { value: 'size_mini', label: 'Mini', group: 'Restaurant Size' },
  { value: 'size_kids', label: 'Kids', group: 'Restaurant Size' },
  { value: 'size_personal', label: 'Personal', group: 'Restaurant Size' },
  { value: 'size_sharing', label: 'Sharing', group: 'Restaurant Size' },
  { value: 'size_family', label: 'Family Size', group: 'Restaurant Size' },
  { value: 'size_single', label: 'Single (Drink)', group: 'Restaurant Size' },
  { value: 'size_double', label: 'Double (Drink)', group: 'Restaurant Size' },
  { value: 'size_short', label: 'Short (Drink)', group: 'Restaurant Size' },
  { value: 'size_tall', label: 'Tall (Drink)', group: 'Restaurant Size' },
  { value: 'size_pint', label: 'Pint', group: 'Restaurant Size' },
  { value: 'size_half_pint', label: 'Half Pint', group: 'Restaurant Size' },
  // Pharma / Medical
  { value: 'tablet', label: 'Tablet', group: 'Pharma' },
  { value: 'capsule', label: 'Capsule', group: 'Pharma' },
  { value: 'strip', label: 'Strip', group: 'Pharma' },
  { value: 'blister', label: 'Blister Pack', group: 'Pharma' },
  { value: 'vial', label: 'Vial', group: 'Pharma' },
  { value: 'ampoule', label: 'Ampoule', group: 'Pharma' },
  { value: 'syringe', label: 'Syringe', group: 'Pharma' },
  { value: 'patch', label: 'Patch', group: 'Pharma' },
  { value: 'inhaler', label: 'Inhaler', group: 'Pharma' },
  { value: 'suppository', label: 'Suppository', group: 'Pharma' },
  { value: 'drops', label: 'Drops', group: 'Pharma' },
  { value: 'spray', label: 'Spray', group: 'Pharma' },
  { value: 'infusion_bag', label: 'Infusion Bag', group: 'Pharma' },
  { value: 'iu', label: 'International Unit (IU)', group: 'Pharma' },
  { value: 'miu', label: 'Million IU (MIU)', group: 'Pharma' },
  // Energy / Power
  { value: 'watt', label: 'Watt (W)', group: 'Energy' },
  { value: 'kw', label: 'Kilowatt (kW)', group: 'Energy' },
  { value: 'mw', label: 'Megawatt (MW)', group: 'Energy' },
  { value: 'kwh', label: 'Kilowatt-Hour (kWh)', group: 'Energy' },
  { value: 'mwh', label: 'Megawatt-Hour (MWh)', group: 'Energy' },
  { value: 'joule', label: 'Joule (J)', group: 'Energy' },
  { value: 'btu', label: 'BTU', group: 'Energy' },
  { value: 'therm', label: 'Therm', group: 'Energy' },
  // Digital / SaaS
  { value: 'seat', label: 'Seat (User)', group: 'Digital' },
  { value: 'license', label: 'License', group: 'Digital' },
  { value: 'instance', label: 'Instance', group: 'Digital' },
  { value: 'credit', label: 'Credit', group: 'Digital' },
  { value: 'token', label: 'Token', group: 'Digital' },
  { value: 'api_call', label: 'API Call', group: 'Digital' },
  { value: 'request', label: 'Request', group: 'Digital' },
  { value: 'transaction', label: 'Transaction', group: 'Digital' },
  { value: 'user', label: 'User', group: 'Digital' },
  { value: 'workspace', label: 'Workspace', group: 'Digital' },
  { value: 'domain', label: 'Domain', group: 'Digital' },
  { value: 'endpoint', label: 'Endpoint', group: 'Digital' },
  { value: 'page_view', label: 'Page View', group: 'Digital' },
  { value: 'impression', label: 'Impression', group: 'Digital' },
  { value: 'click', label: 'Click', group: 'Digital' },
  { value: 'message', label: 'Message', group: 'Digital' },
  { value: 'sms', label: 'SMS', group: 'Digital' },
  { value: 'email_send', label: 'Email Sent', group: 'Digital' },
  { value: 'notification', label: 'Notification', group: 'Digital' },
  // Data
  { value: 'kb', label: 'Kilobyte (KB)', group: 'Data' },
  { value: 'mb', label: 'Megabyte (MB)', group: 'Data' },
  { value: 'gb', label: 'Gigabyte (GB)', group: 'Data' },
  { value: 'tb', label: 'Terabyte (TB)', group: 'Data' },
  { value: 'pb', label: 'Petabyte (PB)', group: 'Data' },
]

export const UOM_GROUPS = [...new Set(UOM_OPTIONS.map(u => u.group))]

export function uomLabel(uom: string): string {
  return UOM_OPTIONS.find(u => u.value === uom)?.label || uom
}

export function formatUomDisplay(
  uomQuantity: number | string | null | undefined,
  uom: string,
): string {
  const opt = UOM_OPTIONS.find(u => u.value === uom)
  const short = (opt?.label || uom).replace(/\s*\(.*\)/, '').trim()
  const qty = uomQuantity === '' || uomQuantity == null ? null : Number(uomQuantity)
  if (qty != null && !Number.isNaN(qty) && qty > 0 && qty !== 1) {
    return `${qty} ${short}`
  }
  return opt?.label || uom
}
