import { useEffect, useState } from 'react'
import { Loader2, Save, Sparkles, Zap } from 'lucide-react'
import { toast } from 'sonner'
import { cn, mediaUrl, solidButtonFocusClassName } from '@/lib/utils'
import { useAIGenerateSEO, useAISuggestBlocks } from '@/hooks/useWebsites'
import type { WebsitePage, WebsiteSite } from '@/types/websites'

const seoFieldClass =
  'w-full rounded-xl border border-input bg-background px-3 py-2 text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring'

export function SEOPanel({
  siteId,
  activePage,
  site,
  onSavePage,
  onSaveSite,
}: {
  siteId: string
  activePage: WebsitePage | null
  site: WebsiteSite
  onSavePage: (data: Record<string, string>) => void
  onSaveSite: (data: Record<string, string>) => void
}) {
  const [tab, setTab] = useState<'page' | 'site'>('page')
  const [seoTitle, setSeoTitle] = useState(activePage?.seo_title || '')
  const [seoDesc, setSeoDesc] = useState(activePage?.seo_description || '')
  const [ogImage, setOgImage] = useState(activePage?.og_image_url || '')
  const [siteTitle, setSiteTitle] = useState((site as { seo_title?: string }).seo_title || '')
  const [siteDesc, setSiteDesc] = useState((site as { seo_description?: string }).seo_description || '')
  const [siteKw, setSiteKw] = useState((site as { seo_keywords?: string }).seo_keywords || '')
  const [aiResult, setAiResult] = useState<{
    seo_title: string
    seo_description: string
    focus_keyword: string
  } | null>(null)
  const aiSEO = useAIGenerateSEO(siteId)
  const suggestBlocks = useAISuggestBlocks(siteId)
  const [suggestResult, setSuggestResult] = useState<{
    reasoning?: string
    blocks?: Array<{ label: string; reason: string }>
  } | null>(null)

  useEffect(() => {
    setSeoTitle(activePage?.seo_title || '')
    setSeoDesc(activePage?.seo_description || '')
    setOgImage(activePage?.og_image_url || '')
  }, [activePage?.id, activePage?.seo_title, activePage?.seo_description, activePage?.og_image_url])

  useEffect(() => {
    setSiteTitle((site as { seo_title?: string }).seo_title || '')
    setSiteDesc((site as { seo_description?: string }).seo_description || '')
    setSiteKw((site as { seo_keywords?: string }).seo_keywords || '')
  }, [site.id, (site as { seo_title?: string }).seo_title, (site as { seo_description?: string }).seo_description, (site as { seo_keywords?: string }).seo_keywords])

  const handleAIGenerate = async () => {
    if (!activePage) return
    try {
      const r = await aiSEO.mutateAsync({
        page_title: activePage.title,
        page_type: activePage.page_type,
        site_description: (site as { description?: string }).description || site.name,
      })
      setAiResult(r)
      toast.success('SEO generated by AI!')
    } catch {
      toast.error('AI SEO generation failed')
    }
  }

  const applyAI = () => {
    if (!aiResult) return
    setSeoTitle(aiResult.seo_title)
    setSeoDesc(aiResult.seo_description)
    setAiResult(null)
  }

  const handleSuggestBlocks = async () => {
    if (!activePage) return
    try {
      const r = await suggestBlocks.mutateAsync({
        page_type: activePage.page_type,
        industry: (site as { description?: string }).description ? undefined : 'general',
      })
      setSuggestResult(r)
    } catch {
      toast.error('Block suggestion failed')
    }
  }

  const titleLen = seoTitle.length
  const descLen = seoDesc.length

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-primary/20 bg-primary/5 px-3 py-2.5 text-[11px] leading-snug text-muted-foreground dark:bg-primary/10">
        <strong className="font-semibold text-foreground">Search listing</strong> controls the title and short description people see in Google and when your link is shared on social media.
      </div>

      <div className="flex gap-0.5 rounded-xl bg-muted/60 p-0.5">
        {(['page', 'site'] as const).map(t => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={cn(
              'flex-1 rounded-lg py-1.5 text-xs font-medium transition-colors',
              tab === t
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground',
            )}
          >
            {t === 'page' ? '📄 This page' : '🌐 Whole site'}
          </button>
        ))}
      </div>

      {tab === 'page' && !activePage && (
        <div className="rounded-xl border border-dashed border-border bg-muted/30 px-4 py-8 text-center text-sm text-muted-foreground">
          Select a page above to edit its search title, summary, and share image.
        </div>
      )}

      {tab === 'page' && activePage && (
        <div className="space-y-3">
          <button
            type="button"
            onClick={handleAIGenerate}
            disabled={aiSEO.isPending}
            className={cn(
              'flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-primary to-info py-2 text-xs font-bold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-60',
              solidButtonFocusClassName,
            )}
          >
            {aiSEO.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
            Write search text with AI
          </button>

          {aiResult && (
            <div className="space-y-2 rounded-xl border border-primary/30 bg-accent p-3">
              <div className="text-xs font-bold uppercase tracking-wide text-primary">AI Suggestion</div>
              <div className="space-y-1">
                <p className="text-xs font-medium text-foreground">Title: {aiResult.seo_title}</p>
                <p className="line-clamp-2 text-xs text-muted-foreground">{aiResult.seo_description}</p>
                <p className="text-xs text-primary">Focus: <strong>{aiResult.focus_keyword}</strong></p>
              </div>
              <div className="flex gap-2">
                <button type="button" onClick={applyAI} className={cn('flex-1 rounded-lg bg-primary py-1.5 text-xs font-bold text-primary-foreground', solidButtonFocusClassName)}>Apply</button>
                <button type="button" onClick={() => setAiResult(null)} className="rounded-lg border border-border bg-background px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground">Dismiss</button>
              </div>
            </div>
          )}

          <div className="space-y-1">
            <div className="flex justify-between">
              <label className="text-xs font-medium text-foreground">Title in Google results</label>
              <span className={cn('text-xs', titleLen > 60 ? 'text-destructive' : titleLen > 50 ? 'text-warning' : 'text-muted-foreground')}>{titleLen}/60</span>
            </div>
            <input
              value={seoTitle}
              onChange={e => setSeoTitle(e.target.value)}
              placeholder={`${activePage.title} | ${site.name}`}
              className={seoFieldClass}
            />
          </div>

          <div className="space-y-1">
            <div className="flex justify-between">
              <label className="text-xs font-medium text-foreground">Short summary for Google</label>
              <span className={cn('text-xs', descLen > 160 ? 'text-destructive' : descLen > 140 ? 'text-warning' : 'text-muted-foreground')}>{descLen}/160</span>
            </div>
            <textarea
              value={seoDesc}
              onChange={e => setSeoDesc(e.target.value)}
              placeholder="Describe this page in 150-160 characters..."
              rows={3}
              className={cn(seoFieldClass, 'resize-none')}
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-medium text-foreground">Share image (social media preview)</label>
            <input
              value={ogImage}
              onChange={e => setOgImage(e.target.value)}
              placeholder="https://... or /uploads/..."
              className={seoFieldClass}
            />
            {ogImage && (
              <img
                src={mediaUrl(ogImage)}
                className="mt-1 h-20 w-full rounded-xl border border-border object-cover"
                alt="OG preview"
                onError={e => { (e.target as HTMLImageElement).style.display = 'none' }}
              />
            )}
          </div>

          <div className="rounded-xl border border-border bg-muted/30 p-3">
            <div className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Search Preview</div>
            <div className="truncate text-xs font-semibold text-info">{seoTitle || `${activePage.title} | ${site.name}`}</div>
            <div className="text-xs text-success">
              {(site as { custom_domain?: string }).custom_domain || `${site.name?.toLowerCase().replace(/\s/g, '')}.site`}/{activePage.slug}
            </div>
            <div className="mt-0.5 line-clamp-2 text-xs text-muted-foreground">
              {seoDesc || 'No meta description set. Add one to improve search ranking.'}
            </div>
          </div>

          <button
            type="button"
            onClick={() => onSavePage({ seo_title: seoTitle, seo_description: seoDesc, og_image_url: ogImage })}
            className={cn(
              'flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-2 text-xs font-bold text-primary-foreground transition-colors hover:bg-primary/90',
              solidButtonFocusClassName,
            )}
          >
            <Save className="w-3.5 h-3.5" /> Save search settings
          </button>

          <div className="space-y-2 border-t border-border pt-3">
            <div className="flex items-center gap-1.5 text-xs font-medium text-foreground">
              <Zap className="h-3.5 w-3.5 text-primary/80" /> AI section ideas
            </div>
            <button
              type="button"
              onClick={handleSuggestBlocks}
              disabled={suggestBlocks.isPending}
              className="flex w-full items-center justify-center gap-2 rounded-xl border border-primary/30 py-2 text-xs font-medium text-primary hover:bg-accent"
            >
              {suggestBlocks.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
              Suggest sections for this page
            </button>
            {suggestResult && (
              <div className="space-y-1.5">
                <p className="text-xs italic text-muted-foreground">{suggestResult.reasoning}</p>
                <div className="space-y-1">
                  {suggestResult.blocks?.map((b, i) => (
                    <div key={i} className="flex items-start gap-2 rounded-lg bg-muted/40 p-2">
                      <span className="shrink-0 text-xs font-bold text-primary">{i + 1}.</span>
                      <div>
                        <div className="text-xs font-medium text-foreground">{b.label}</div>
                        <div className="text-xs text-muted-foreground">{b.reason}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {tab === 'site' && (
        <div className="space-y-3">
          <div className="space-y-1">
            <label className="text-xs font-medium text-foreground">Default title in Google</label>
            <input
              value={siteTitle}
              onChange={e => setSiteTitle(e.target.value)}
              placeholder={site.name}
              className={seoFieldClass}
            />
          </div>
          <div className="space-y-1">
            <label className="text-xs font-medium text-foreground">Default summary for Google</label>
            <textarea
              value={siteDesc}
              onChange={e => setSiteDesc(e.target.value)}
              placeholder="Overall site description for search engines..."
              rows={3}
              className={cn(seoFieldClass, 'resize-none')}
            />
          </div>
          <div className="space-y-1">
            <label className="text-xs font-medium text-foreground">Keywords (comma-separated)</label>
            <input
              value={siteKw}
              onChange={e => setSiteKw(e.target.value)}
              placeholder="keyword1, keyword2, keyword3..."
              className={seoFieldClass}
            />
          </div>
          <button
            type="button"
            onClick={() => onSaveSite({ seo_title: siteTitle, seo_description: siteDesc, seo_keywords: siteKw })}
            className={cn(
              'flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-2 text-xs font-bold text-primary-foreground transition-colors hover:bg-primary/90',
              solidButtonFocusClassName,
            )}
          >
            <Save className="w-3.5 h-3.5" /> Save site search settings
          </button>
        </div>
      )}
    </div>
  )
}
