import { useEffect, useState } from 'react'
import { Loader2, Save, Sparkles, Zap } from 'lucide-react'
import { toast } from 'sonner'
import { cn, mediaUrl } from '@/lib/utils'
import { useAIGenerateSEO, useAISuggestBlocks } from '@/hooks/useWebsites'
import type { WebsitePage, WebsiteSite } from '@/types/websites'

export function SEOPanel({
  siteId,
  activePage,
  site,
  onSavePage,
  onSaveSite,
}: {
  siteId: string
  activePage: WebsitePage | null
  site: WebsiteSite
  onSavePage: (data: Record<string, string>) => void
  onSaveSite: (data: Record<string, string>) => void
}) {
  const [tab, setTab] = useState<'page' | 'site'>('page')
  const [seoTitle, setSeoTitle] = useState(activePage?.seo_title || '')
  const [seoDesc, setSeoDesc] = useState(activePage?.seo_description || '')
  const [ogImage, setOgImage] = useState(activePage?.og_image_url || '')
  const [siteTitle, setSiteTitle] = useState((site as { seo_title?: string }).seo_title || '')
  const [siteDesc, setSiteDesc] = useState((site as { seo_description?: string }).seo_description || '')
  const [siteKw, setSiteKw] = useState((site as { seo_keywords?: string }).seo_keywords || '')
  const [aiResult, setAiResult] = useState<{
    seo_title: string
    seo_description: string
    focus_keyword: string
  } | null>(null)
  const aiSEO = useAIGenerateSEO(siteId)
  const suggestBlocks = useAISuggestBlocks(siteId)
  const [suggestResult, setSuggestResult] = useState<{
    reasoning?: string
    blocks?: Array<{ label: string; reason: string }>
  } | null>(null)

  useEffect(() => {
    setSeoTitle(activePage?.seo_title || '')
    setSeoDesc(activePage?.seo_description || '')
    setOgImage(activePage?.og_image_url || '')
  }, [activePage?.id, activePage?.seo_title, activePage?.seo_description, activePage?.og_image_url])

  useEffect(() => {
    setSiteTitle((site as { seo_title?: string }).seo_title || '')
    setSiteDesc((site as { seo_description?: string }).seo_description || '')
    setSiteKw((site as { seo_keywords?: string }).seo_keywords || '')
  }, [site.id, (site as { seo_title?: string }).seo_title, (site as { seo_description?: string }).seo_description, (site as { seo_keywords?: string }).seo_keywords])

  const handleAIGenerate = async () => {
    if (!activePage) return
    try {
      const r = await aiSEO.mutateAsync({
        page_title: activePage.title,
        page_type: activePage.page_type,
        site_description: (site as { description?: string }).description || site.name,
      })
      setAiResult(r)
      toast.success('SEO generated by AI!')
    } catch {
      toast.error('AI SEO generation failed')
    }
  }

  const applyAI = () => {
    if (!aiResult) return
    setSeoTitle(aiResult.seo_title)
    setSeoDesc(aiResult.seo_description)
    setAiResult(null)
  }

  const handleSuggestBlocks = async () => {
    if (!activePage) return
    try {
      const r = await suggestBlocks.mutateAsync({
        page_type: activePage.page_type,
        industry: (site as { description?: string }).description ? undefined : 'general',
      })
      setSuggestResult(r)
    } catch {
      toast.error('Block suggestion failed')
    }
  }

  const titleLen = seoTitle.length
  const descLen = seoDesc.length

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-sky-100 bg-sky-50/80 px-3 py-2.5 text-[11px] text-gray-600 leading-snug">
        <strong className="font-semibold text-gray-800">Search listing</strong> controls the title and short description people see in Google and when your link is shared on social media.
      </div>

      <div className="flex bg-gray-100 rounded-xl p-0.5 gap-0.5">
        {(['page', 'site'] as const).map(t => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={cn(
              'flex-1 py-1.5 rounded-lg text-xs font-medium transition-colors',
              tab === t ? 'bg-white text-gray-800 shadow-sm' : 'text-gray-500 hover:text-gray-700',
            )}
          >
            {t === 'page' ? '📄 This page' : '🌐 Whole site'}
          </button>
        ))}
      </div>

      {tab === 'page' && !activePage && (
        <div className="rounded-xl border border-dashed border-gray-200 bg-gray-50 px-4 py-8 text-center text-sm text-gray-500">
          Select a page above to edit its search title, summary, and share image.
        </div>
      )}

      {tab === 'page' && activePage && (
        <div className="space-y-3">
          <button
            type="button"
            onClick={handleAIGenerate}
            disabled={aiSEO.isPending}
            className="w-full py-2 bg-gradient-to-r from-primary to-info text-white text-xs font-bold rounded-xl flex items-center justify-center gap-2 hover:opacity-90 transition-opacity"
          >
            {aiSEO.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
            Write search text with AI
          </button>

          {aiResult && (
            <div className="p-3 bg-accent border border-primary/30 rounded-xl space-y-2">
              <div className="text-xs font-bold text-primary uppercase tracking-wide">AI Suggestion</div>
              <div className="space-y-1">
                <p className="text-xs font-medium text-gray-700">Title: {aiResult.seo_title}</p>
                <p className="text-xs text-gray-600 line-clamp-2">{aiResult.seo_description}</p>
                <p className="text-xs text-primary">Focus: <strong>{aiResult.focus_keyword}</strong></p>
              </div>
              <div className="flex gap-2">
                <button type="button" onClick={applyAI} className="flex-1 py-1.5 bg-primary text-white text-xs font-bold rounded-lg">Apply</button>
                <button type="button" onClick={() => setAiResult(null)} className="px-3 py-1.5 bg-white border border-gray-200 text-gray-500 text-xs rounded-lg">Dismiss</button>
              </div>
            </div>
          )}

          <div className="space-y-1">
            <div className="flex justify-between">
              <label className="text-xs font-medium text-gray-700">Title in Google results</label>
              <span className={cn('text-xs', titleLen > 60 ? 'text-red-500' : titleLen > 50 ? 'text-amber-500' : 'text-gray-400')}>{titleLen}/60</span>
            </div>
            <input
              value={seoTitle}
              onChange={e => setSeoTitle(e.target.value)}
              placeholder={`${activePage.title} | ${site.name}`}
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>

          <div className="space-y-1">
            <div className="flex justify-between">
              <label className="text-xs font-medium text-gray-700">Short summary for Google</label>
              <span className={cn('text-xs', descLen > 160 ? 'text-red-500' : descLen > 140 ? 'text-amber-500' : 'text-gray-400')}>{descLen}/160</span>
            </div>
            <textarea
              value={seoDesc}
              onChange={e => setSeoDesc(e.target.value)}
              placeholder="Describe this page in 150-160 characters..."
              rows={3}
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs resize-none focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-medium text-gray-700">Share image (social media preview)</label>
            <input
              value={ogImage}
              onChange={e => setOgImage(e.target.value)}
              placeholder="https://... or /uploads/..."
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-ring"
            />
            {ogImage && (
              <img
                src={mediaUrl(ogImage)}
                className="w-full h-20 object-cover rounded-xl border border-gray-100 mt-1"
                alt="OG preview"
                onError={e => { (e.target as HTMLImageElement).style.display = 'none' }}
              />
            )}
          </div>

          <div className="p-3 bg-white border border-gray-200 rounded-xl">
            <div className="text-xs text-gray-400 mb-1.5 font-semibold uppercase tracking-wide">Search Preview</div>
            <div className="text-xs text-blue-700 font-semibold truncate">{seoTitle || `${activePage.title} | ${site.name}`}</div>
            <div className="text-xs text-green-700">
              {(site as { custom_domain?: string }).custom_domain || `${site.name?.toLowerCase().replace(/\s/g, '')}.site`}/{activePage.slug}
            </div>
            <div className="text-xs text-gray-600 mt-0.5 line-clamp-2">
              {seoDesc || 'No meta description set. Add one to improve search ranking.'}
            </div>
          </div>

          <button
            type="button"
            onClick={() => onSavePage({ seo_title: seoTitle, seo_description: seoDesc, og_image_url: ogImage })}
            className="w-full py-2 bg-gray-800 text-white text-xs font-bold rounded-xl hover:bg-gray-700 transition-colors flex items-center justify-center gap-2"
          >
            <Save className="w-3.5 h-3.5" /> Save search settings
          </button>

          <div className="border-t border-gray-100 pt-3 space-y-2">
            <div className="text-xs font-medium text-gray-700 flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-primary/80" /> AI section ideas
            </div>
            <button
              type="button"
              onClick={handleSuggestBlocks}
              disabled={suggestBlocks.isPending}
              className="w-full py-2 border border-primary/30 text-primary text-xs font-medium rounded-xl hover:bg-accent flex items-center justify-center gap-2"
            >
              {suggestBlocks.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
              Suggest sections for this page
            </button>
            {suggestResult && (
              <div className="space-y-1.5">
                <p className="text-xs text-gray-500 italic">{suggestResult.reasoning}</p>
                <div className="space-y-1">
                  {suggestResult.blocks?.map((b, i) => (
                    <div key={i} className="flex items-start gap-2 p-2 bg-gray-50 rounded-lg">
                      <span className="text-xs font-bold text-primary shrink-0">{i + 1}.</span>
                      <div>
                        <div className="text-xs font-medium text-gray-700">{b.label}</div>
                        <div className="text-xs text-gray-400">{b.reason}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {tab === 'site' && (
        <div className="space-y-3">
          <div className="space-y-1">
            <label className="text-xs font-medium text-gray-700">Default title in Google</label>
            <input
              value={siteTitle}
              onChange={e => setSiteTitle(e.target.value)}
              placeholder={site.name}
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div className="space-y-1">
            <label className="text-xs font-medium text-gray-700">Default summary for Google</label>
            <textarea
              value={siteDesc}
              onChange={e => setSiteDesc(e.target.value)}
              placeholder="Overall site description for search engines..."
              rows={3}
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs resize-none focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div className="space-y-1">
            <label className="text-xs font-medium text-gray-700">Keywords (comma-separated)</label>
            <input
              value={siteKw}
              onChange={e => setSiteKw(e.target.value)}
              placeholder="keyword1, keyword2, keyword3..."
              className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <button
            type="button"
            onClick={() => onSaveSite({ seo_title: siteTitle, seo_description: siteDesc, seo_keywords: siteKw })}
            className="w-full py-2 bg-gray-800 text-white text-xs font-bold rounded-xl hover:bg-gray-700 transition-colors flex items-center justify-center gap-2"
          >
            <Save className="w-3.5 h-3.5" /> Save site search settings
          </button>
        </div>
      )}
    </div>
  )
}
