"""add customer cart order payment tables

Revision ID: 48b883dfccbe
Revises: 5222b36e2a56
Create Date: 2026-02-11 01:02:22.111205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48b883dfccbe'
down_revision: Union[str, None] = '5222b36e2a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('shipping_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_address_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_vendor_email', 'customer', ['vendor_id', 'email'], unique=True)
    op.create_index(op.f('ix_customer_vendor_id'), 'customer', ['vendor_id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_customer_id'), 'cart', ['customer_id'], unique=False)
    op.create_index('ix_cart_vendor_customer', 'cart', ['vendor_id', 'customer_id'], unique=True)
    op.create_index(op.f('ix_cart_vendor_id'), 'cart', ['vendor_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index('ix_order_vendor_created', 'order', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_vendor_id'), 'order', ['vendor_id'], unique=False)
    op.create_index('ix_order_vendor_status', 'order', ['vendor_id', 'status'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('gateway_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_vendor_id'), 'payment', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_vendor_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_order_vendor_status', table_name='order')
    op.drop_index(op.f('ix_order_vendor_id'), table_name='order')
    op.drop_index('ix_order_vendor_created', table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_cart_vendor_id'), table_name='cart')
    op.drop_index('ix_cart_vendor_customer', table_name='cart')
    op.drop_index(op.f('ix_cart_customer_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_customer_vendor_id'), table_name='customer')
    op.drop_index('ix_customer_vendor_email', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
