"""add_booking_and_notification_tables

Revision ID: 4c9a19eb0609
Revises: b197344ca7b8
Create Date: 2026-03-16 23:37:46.564237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c9a19eb0609'
down_revision: Union[str, None] = 'b197344ca7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_category_applies', 'vendor_category', ['vendor_id', 'applies_to'], unique=False)
    op.create_index('idx_vendor_category_slug', 'vendor_category', ['vendor_id', 'slug'], unique=True)
    op.create_index('idx_vendor_category_vendor', 'vendor_category', ['vendor_id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('booking_number', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('service_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_booking_number'), 'booking', ['booking_number'], unique=False)
    op.create_index(op.f('ix_booking_customer_id'), 'booking', ['customer_id'], unique=False)
    op.create_index('ix_booking_vendor_date', 'booking', ['vendor_id', 'booking_date'], unique=False)
    op.create_index(op.f('ix_booking_vendor_id'), 'booking', ['vendor_id'], unique=False)
    op.create_index('ix_booking_vendor_status', 'booking', ['vendor_id', 'status'], unique=False)
    op.create_index('uq_booking_vendor_number', 'booking', ['vendor_id', 'booking_number'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_customer_id'), 'notification', ['customer_id'], unique=False)
    op.create_index('ix_notification_customer_read', 'notification', ['customer_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_notification_vendor_created', 'notification', ['vendor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_vendor_id'), 'notification', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_vendor_id'), table_name='notification')
    op.drop_index('ix_notification_vendor_created', table_name='notification')
    op.drop_index('ix_notification_user_read', table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index('ix_notification_customer_read', table_name='notification')
    op.drop_index(op.f('ix_notification_customer_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index('uq_booking_vendor_number', table_name='booking')
    op.drop_index('ix_booking_vendor_status', table_name='booking')
    op.drop_index(op.f('ix_booking_vendor_id'), table_name='booking')
    op.drop_index('ix_booking_vendor_date', table_name='booking')
    op.drop_index(op.f('ix_booking_customer_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_booking_number'), table_name='booking')
    op.drop_table('booking')
    op.drop_index('idx_vendor_category_vendor', table_name='vendor_category')
    op.drop_index('idx_vendor_category_slug', table_name='vendor_category')
    op.drop_index('idx_vendor_category_applies', table_name='vendor_category')
    op.drop_table('vendor_category')
    # ### end Alembic commands ###
