"""fix_order_number_unique_constraint

Revision ID: 729ec2d9abae
Revises: ca70a6a5dd5b
Create Date: 2026-02-25 00:18:23.038332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729ec2d9abae'
down_revision: Union[str, None] = 'ca70a6a5dd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_order_number', table_name='order')
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=False)
    op.create_index('uq_order_vendor_number', 'order', ['vendor_id', 'order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_order_vendor_number', table_name='order')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.create_index('ix_order_order_number', 'order', ['order_number'], unique=True)
    # ### end Alembic commands ###
