"""fix_pos_txn_number_unique_constraint

Revision ID: 85981fc527cf
Revises: 729ec2d9abae
Create Date: 2026-02-25 00:21:32.871266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85981fc527cf'
down_revision: Union[str, None] = '729ec2d9abae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pos_transaction_transaction_number', table_name='pos_transaction')
    op.create_index(op.f('ix_pos_transaction_transaction_number'), 'pos_transaction', ['transaction_number'], unique=False)
    op.create_index('uq_pos_txn_vendor_number', 'pos_transaction', ['vendor_id', 'transaction_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pos_txn_vendor_number', table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_transaction_number'), table_name='pos_transaction')
    op.create_index('ix_pos_transaction_transaction_number', 'pos_transaction', ['transaction_number'], unique=True)
    # ### end Alembic commands ###
