"""employee_notes

Revision ID: b8976eee49a5
Revises: b9ea052458ab
Create Date: 2026-04-16 10:21:08.185127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8976eee49a5'
down_revision: Union[str, None] = 'b9ea052458ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_employee_profile', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_employee_profile', 'notes')
    # ### end Alembic commands ###
