"""employee_exit_family_tagged_to

Revision ID: b9ea052458ab
Revises: fe01c6dbd535
Create Date: 2026-04-16 10:00:51.210736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9ea052458ab'
down_revision: Union[str, None] = 'fe01c6dbd535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_employee_profile', sa.Column('tagged_to_type', sa.String(length=30), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('tagged_to_label', sa.String(length=100), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('lwd', sa.Date(), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('exit_reason', sa.String(length=50), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('exit_interview_notes', sa.Text(), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('exit_clearance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('notice_served', sa.Boolean(), nullable=True))
    op.add_column('hr_employee_profile', sa.Column('family_members', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_employee_profile', 'family_members')
    op.drop_column('hr_employee_profile', 'notice_served')
    op.drop_column('hr_employee_profile', 'exit_clearance')
    op.drop_column('hr_employee_profile', 'exit_interview_notes')
    op.drop_column('hr_employee_profile', 'exit_reason')
    op.drop_column('hr_employee_profile', 'lwd')
    op.drop_column('hr_employee_profile', 'tagged_to_label')
    op.drop_column('hr_employee_profile', 'tagged_to_type')
    # ### end Alembic commands ###
