"""add_pos_invoice_coupon_lead_tables

Revision ID: ca70a6a5dd5b
Revises: 48b883dfccbe
Create Date: 2026-02-20 00:44:25.363647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca70a6a5dd5b'
down_revision: Union[str, None] = '48b883dfccbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('radius_km', sa.Integer(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_category', 'lead', ['category'], unique=False)
    op.create_index(op.f('ix_lead_customer_id'), 'lead', ['customer_id'], unique=False)
    op.create_index('ix_lead_status', 'lead', ['status'], unique=False)
    op.create_table('coupon',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_per_customer', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('applicable_to', sa.String(length=20), nullable=True),
    sa.Column('applicable_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=False)
    op.create_index('ix_coupon_vendor_active', 'coupon', ['vendor_id', 'is_active'], unique=False)
    op.create_index('ix_coupon_vendor_code', 'coupon', ['vendor_id', 'code'], unique=True)
    op.create_index(op.f('ix_coupon_vendor_id'), 'coupon', ['vendor_id'], unique=False)
    op.create_table('pos_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closing_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_returns', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('cash_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('upi_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('card_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pos_session_vendor_date', 'pos_session', ['vendor_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_pos_session_vendor_id'), 'pos_session', ['vendor_id'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_time', sa.String(length=100), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_lead_id'), 'quote', ['lead_id'], unique=False)
    op.create_index('ix_quote_lead_vendor', 'quote', ['lead_id', 'vendor_id'], unique=True)
    op.create_index(op.f('ix_quote_vendor_id'), 'quote', ['vendor_id'], unique=False)
    op.create_table('coupon_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usage_coupon_id'), 'coupon_usage', ['coupon_id'], unique=False)
    op.create_table('inventory_movement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_created', 'inventory_movement', ['created_at'], unique=False)
    op.create_index('idx_inv_product', 'inventory_movement', ['product_id'], unique=False)
    op.create_index('idx_inv_ref', 'inventory_movement', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_inv_type', 'inventory_movement', ['movement_type'], unique=False)
    op.create_index('idx_inv_variant', 'inventory_movement', ['variant_id'], unique=False)
    op.create_index('idx_inv_vendor', 'inventory_movement', ['vendor_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_gstin', sa.String(length=15), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_gstin', sa.String(length=15), nullable=True),
    sa.Column('vendor_pan', sa.String(length=10), nullable=True),
    sa.Column('vendor_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('reference_invoice_id', sa.UUID(), nullable=True),
    sa.Column('converted_from_id', sa.UUID(), nullable=True),
    sa.Column('is_gst', sa.Boolean(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('is_inter_state', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=False)
    op.create_index('ix_invoice_number', 'invoice', ['vendor_id', 'invoice_number'], unique=True)
    op.create_index(op.f('ix_invoice_vendor_id'), 'invoice', ['vendor_id'], unique=False)
    op.create_index('ix_invoice_vendor_status', 'invoice', ['vendor_id', 'status'], unique=False)
    op.create_index('ix_invoice_vendor_type', 'invoice', ['vendor_id', 'invoice_type'], unique=False)
    op.create_table('pos_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('transaction_number', sa.String(length=30), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cash_received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('return_of', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pos_session.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_transaction_session_id'), 'pos_transaction', ['session_id'], unique=False)
    op.create_index(op.f('ix_pos_transaction_transaction_number'), 'pos_transaction', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_pos_transaction_vendor_id'), 'pos_transaction', ['vendor_id'], unique=False)
    op.create_index('ix_pos_txn_session', 'pos_transaction', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_pos_txn_vendor_created', 'pos_transaction', ['vendor_id', 'created_at'], unique=False)
    # Add columns if they don't exist (idempotent migration fix)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    product_cols = [c['name'] for c in inspector.get_columns('product')]
    service_cols = [c['name'] for c in inspector.get_columns('service')]

    if 'is_taxable' not in product_cols:
        op.add_column('product', sa.Column('is_taxable', sa.BOOLEAN(), server_default=sa.text('true'), nullable=True))
    else:
        op.alter_column('product', 'is_taxable',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('true'))

    if 'is_taxable' not in service_cols:
        op.add_column('service', sa.Column('is_taxable', sa.BOOLEAN(), server_default=sa.text('true'), nullable=True))
    else:
        op.alter_column('service', 'is_taxable',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('true'))

    if 'uom' not in service_cols:
        op.add_column('service', sa.Column('uom', sa.VARCHAR(length=30), server_default=sa.text("'fixed'::character varying"), nullable=True))
    else:
        op.alter_column('service', 'uom',
                   existing_type=sa.VARCHAR(length=30),
                   nullable=True,
                   existing_server_default=sa.text("'fixed'::character varying"))

    if 'service_mode' not in service_cols:
        op.add_column('service', sa.Column('service_mode', sa.VARCHAR(length=30), server_default=sa.text("'in_store'::character varying"), nullable=True))
    else:
        op.alter_column('service', 'service_mode',
                   existing_type=sa.VARCHAR(length=30),
                   nullable=True,
                   existing_server_default=sa.text("'in_store'::character varying"))
    vendor_cols = [c['name'] for c in inspector.get_columns('vendor')]
    existing_tables = inspector.get_table_names()
    vendor_build_cols = [c['name'] for c in inspector.get_columns('vendor_app_build')] if 'vendor_app_build' in existing_tables else []

    if 'is_gst_registered' not in vendor_cols:
        op.add_column('vendor', sa.Column('is_gst_registered', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    else:
        op.alter_column('vendor', 'is_gst_registered',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))

    if 'app_config' not in vendor_cols:
        op.add_column('vendor', sa.Column('app_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    else:
        op.alter_column('vendor', 'app_config',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   nullable=True,
                   existing_server_default=sa.text("'{}'::jsonb"))

    # Drop indexes only if they exist
    vendor_indexes = [i['name'] for i in inspector.get_indexes('vendor')]
    if 'idx_vendor_approved_location' in vendor_indexes:
        op.drop_index('idx_vendor_approved_location', table_name='vendor', postgresql_where="(((status)::text = 'approved'::text) AND (latitude IS NOT NULL) AND (longitude IS NOT NULL))")
    if 'idx_vendor_lat_lon' in vendor_indexes:
        op.drop_index('idx_vendor_lat_lon', table_name='vendor', postgresql_where='((latitude IS NOT NULL) AND (longitude IS NOT NULL))')

    if 'vendor_app_build' in existing_tables:
        if 'config_snapshot' not in vendor_build_cols:
            op.add_column('vendor_app_build', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
        else:
            op.alter_column('vendor_app_build', 'config_snapshot',
                       existing_type=postgresql.JSONB(astext_type=sa.Text()),
                       nullable=True,
                       existing_server_default=sa.text("'{}'::jsonb"))

        if 'created_at' not in vendor_build_cols:
            op.add_column('vendor_app_build', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
        else:
            op.alter_column('vendor_app_build', 'created_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       nullable=True,
                       existing_server_default=sa.text('now()'))

        if 'updated_at' not in vendor_build_cols:
            op.add_column('vendor_app_build', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
        else:
            op.alter_column('vendor_app_build', 'updated_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       nullable=True,
                       existing_server_default=sa.text('now()'))

    if 'vendor_role' in existing_tables:
        vendor_role_indexes = [i['name'] for i in inspector.get_indexes('vendor_role')]
        if 'idx_vendor_role_vendor' in vendor_role_indexes:
            op.drop_index('idx_vendor_role_vendor', table_name='vendor_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vendor_role_vendor', 'vendor_role', ['vendor_id'], unique=False)
    op.alter_column('vendor_app_build', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_app_build', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_app_build', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('idx_vendor_lat_lon', 'vendor', ['latitude', 'longitude'], unique=False, postgresql_where='((latitude IS NOT NULL) AND (longitude IS NOT NULL))')
    op.create_index('idx_vendor_approved_location', 'vendor', ['status', 'latitude', 'longitude'], unique=False, postgresql_where="(((status)::text = 'approved'::text) AND (latitude IS NOT NULL) AND (longitude IS NOT NULL))")
    op.alter_column('vendor', 'app_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('vendor', 'is_gst_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('service', 'service_mode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'in_store'::character varying"))
    op.alter_column('service', 'uom',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'fixed'::character varying"))
    op.alter_column('service', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('product', 'is_taxable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_pos_txn_vendor_created', table_name='pos_transaction')
    op.drop_index('ix_pos_txn_session', table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_vendor_id'), table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_transaction_number'), table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_session_id'), table_name='pos_transaction')
    op.drop_table('pos_transaction')
    op.drop_index('ix_invoice_vendor_type', table_name='invoice')
    op.drop_index('ix_invoice_vendor_status', table_name='invoice')
    op.drop_index(op.f('ix_invoice_vendor_id'), table_name='invoice')
    op.drop_index('ix_invoice_number', table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('idx_inv_vendor', table_name='inventory_movement')
    op.drop_index('idx_inv_variant', table_name='inventory_movement')
    op.drop_index('idx_inv_type', table_name='inventory_movement')
    op.drop_index('idx_inv_ref', table_name='inventory_movement')
    op.drop_index('idx_inv_product', table_name='inventory_movement')
    op.drop_index('idx_inv_created', table_name='inventory_movement')
    op.drop_table('inventory_movement')
    op.drop_index(op.f('ix_coupon_usage_coupon_id'), table_name='coupon_usage')
    op.drop_table('coupon_usage')
    op.drop_index(op.f('ix_quote_vendor_id'), table_name='quote')
    op.drop_index('ix_quote_lead_vendor', table_name='quote')
    op.drop_index(op.f('ix_quote_lead_id'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_pos_session_vendor_id'), table_name='pos_session')
    op.drop_index('ix_pos_session_vendor_date', table_name='pos_session')
    op.drop_table('pos_session')
    op.drop_index(op.f('ix_coupon_vendor_id'), table_name='coupon')
    op.drop_index('ix_coupon_vendor_code', table_name='coupon')
    op.drop_index('ix_coupon_vendor_active', table_name='coupon')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    op.drop_index('ix_lead_status', table_name='lead')
    op.drop_index(op.f('ix_lead_customer_id'), table_name='lead')
    op.drop_index('ix_lead_category', table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
