"""Add full CRM tables (accounts, contacts, leads, pipelines, stages, deals,
activities, communications, tickets, KB, segments, templates, campaigns,
workflows, integrations, audit, AI insights, chat, journey, intake tokens).

Revision ID: crm001_add_crm_tables
Revises: e1f2a3b4c5d6
Create Date: 2026-04-18

Mirrors the schema produced by ``app.database.ensure_crm_tables`` and
``app.models.crm``. All statements use ``IF NOT EXISTS`` so this migration is
safe to run on databases where the tables were already auto-created at boot.
"""
from alembic import op


revision = "crm001_add_crm_tables"
down_revision = "e1f2a3b4c5d6"
branch_labels = None
depends_on = None


# ── DDL: keep this list in lock-step with app/database.py:ensure_crm_tables ──
DDL_STATEMENTS: list[str] = [
    # ── Accounts ─────────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_account (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        parent_id UUID REFERENCES crm_account(id) ON DELETE SET NULL,
        name VARCHAR(255) NOT NULL,
        industry VARCHAR(100),
        region VARCHAR(100),
        website VARCHAR(500),
        phone VARCHAR(50),
        email VARCHAR(255),
        annual_revenue NUMERIC(14,2),
        employee_count INTEGER,
        billing_address JSONB DEFAULT '{}'::jsonb,
        shipping_address JSONB DEFAULT '{}'::jsonb,
        tags JSONB DEFAULT '[]'::jsonb,
        custom_fields JSONB DEFAULT '{}'::jsonb,
        notes TEXT,
        owner_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_account_vendor_id ON crm_account(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_account_vendor_name ON crm_account(vendor_id, name);",
    "CREATE INDEX IF NOT EXISTS ix_crm_account_owner ON crm_account(owner_id);",
    # ── Contacts ─────────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_contact (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        account_id UUID REFERENCES crm_account(id) ON DELETE SET NULL,
        customer_id UUID REFERENCES customer(id) ON DELETE SET NULL,
        owner_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        first_name VARCHAR(120) NOT NULL,
        last_name VARCHAR(120),
        title VARCHAR(120),
        email VARCHAR(255),
        phone VARCHAR(50),
        mobile VARCHAR(50),
        address JSONB DEFAULT '{}'::jsonb,
        tags JSONB DEFAULT '[]'::jsonb,
        custom_fields JSONB DEFAULT '{}'::jsonb,
        notes TEXT,
        lifecycle_stage VARCHAR(40) DEFAULT 'lead',
        lead_source VARCHAR(80),
        do_not_email BOOLEAN DEFAULT FALSE,
        do_not_call BOOLEAN DEFAULT FALSE,
        is_active BOOLEAN DEFAULT TRUE,
        last_activity_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_contact_vendor_id ON crm_contact(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_contact_vendor_email ON crm_contact(vendor_id, email);",
    "CREATE INDEX IF NOT EXISTS ix_crm_contact_vendor_phone ON crm_contact(vendor_id, phone);",
    "CREATE INDEX IF NOT EXISTS ix_crm_contact_account ON crm_contact(account_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_contact_owner ON crm_contact(owner_id);",
    # ── Pipelines / Stages ───────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_pipeline (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        description TEXT,
        is_default BOOLEAN DEFAULT FALSE,
        is_active BOOLEAN DEFAULT TRUE,
        sort_order INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_pipeline_vendor ON crm_pipeline(vendor_id);",
    """CREATE TABLE IF NOT EXISTS crm_stage (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        pipeline_id UUID NOT NULL REFERENCES crm_pipeline(id) ON DELETE CASCADE,
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        probability NUMERIC(5,2) DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        is_won BOOLEAN DEFAULT FALSE,
        is_lost BOOLEAN DEFAULT FALSE,
        color VARCHAR(20),
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_stage_pipeline ON crm_stage(pipeline_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_stage_vendor ON crm_stage(vendor_id);",
    # ── Deals ────────────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_deal (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        pipeline_id UUID NOT NULL REFERENCES crm_pipeline(id) ON DELETE RESTRICT,
        stage_id UUID NOT NULL REFERENCES crm_stage(id) ON DELETE RESTRICT,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        account_id UUID REFERENCES crm_account(id) ON DELETE SET NULL,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        owner_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        amount NUMERIC(14,2) DEFAULT 0,
        currency VARCHAR(3) DEFAULT 'INR',
        probability NUMERIC(5,2),
        expected_close_date TIMESTAMPTZ,
        closed_at TIMESTAMPTZ,
        status VARCHAR(20) DEFAULT 'open',
        lost_reason VARCHAR(255),
        won_reason VARCHAR(255),
        source VARCHAR(80),
        sort_order INTEGER DEFAULT 0,
        tags JSONB DEFAULT '[]'::jsonb,
        custom_fields JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_deal_vendor ON crm_deal(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_deal_vendor_stage ON crm_deal(vendor_id, stage_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_deal_owner ON crm_deal(owner_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_deal_status ON crm_deal(vendor_id, status);",
    # ── Leads ────────────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_lead (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        first_name VARCHAR(120),
        last_name VARCHAR(120),
        company VARCHAR(255),
        email VARCHAR(255),
        phone VARCHAR(50),
        title VARCHAR(120),
        website VARCHAR(500),
        source VARCHAR(80),
        source_campaign VARCHAR(255),
        status VARCHAR(40) DEFAULT 'new',
        score INTEGER DEFAULT 0,
        rating VARCHAR(20),
        assigned_to UUID REFERENCES "user"(id) ON DELETE SET NULL,
        notes TEXT,
        intake_payload JSONB DEFAULT '{}'::jsonb,
        custom_fields JSONB DEFAULT '{}'::jsonb,
        tags JSONB DEFAULT '[]'::jsonb,
        converted_at TIMESTAMPTZ,
        converted_contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        converted_account_id UUID REFERENCES crm_account(id) ON DELETE SET NULL,
        converted_deal_id UUID REFERENCES crm_deal(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_lead_vendor ON crm_lead(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_lead_vendor_status ON crm_lead(vendor_id, status);",
    "CREATE INDEX IF NOT EXISTS ix_crm_lead_assigned ON crm_lead(assigned_to);",
    "CREATE INDEX IF NOT EXISTS ix_crm_lead_email ON crm_lead(vendor_id, email);",
    # ── Activities ───────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_activity (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        owner_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        type VARCHAR(20) NOT NULL,
        subject VARCHAR(255) NOT NULL,
        description TEXT,
        related_type VARCHAR(30),
        related_id UUID,
        due_at TIMESTAMPTZ,
        reminder_at TIMESTAMPTZ,
        completed_at TIMESTAMPTZ,
        duration_minutes INTEGER,
        priority VARCHAR(20) DEFAULT 'normal',
        status VARCHAR(20) DEFAULT 'open',
        location VARCHAR(255),
        meeting_url VARCHAR(500),
        outcome VARCHAR(255),
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_activity_vendor ON crm_activity(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_activity_vendor_owner ON crm_activity(vendor_id, owner_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_activity_related ON crm_activity(related_type, related_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_activity_due ON crm_activity(vendor_id, due_at);",
    # ── Communication logs ───────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_communication_log (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        channel VARCHAR(20) NOT NULL,
        direction VARCHAR(10) DEFAULT 'outbound',
        subject VARCHAR(255),
        body TEXT,
        occurred_at TIMESTAMPTZ DEFAULT now(),
        related_type VARCHAR(30),
        related_id UUID,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        recorded_by UUID REFERENCES "user"(id) ON DELETE SET NULL,
        external_id VARCHAR(255),
        provider VARCHAR(40),
        status VARCHAR(40),
        sentiment VARCHAR(20),
        metadata JSONB DEFAULT '{}'::jsonb,
        attachments JSONB DEFAULT '[]'::jsonb
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_comm_vendor ON crm_communication_log(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_comm_vendor_occurred ON crm_communication_log(vendor_id, occurred_at);",
    "CREATE INDEX IF NOT EXISTS ix_crm_comm_related ON crm_communication_log(related_type, related_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_comm_contact ON crm_communication_log(contact_id);",
    # ── Call recordings ──────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_call_recording (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        communication_id UUID REFERENCES crm_communication_log(id) ON DELETE CASCADE,
        url VARCHAR(500),
        duration_seconds INTEGER,
        transcript TEXT,
        sentiment VARCHAR(20),
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_call_recording_vendor ON crm_call_recording(vendor_id);",
    # ── SLA policies / tickets / comments / KB ───────────────────────
    """CREATE TABLE IF NOT EXISTS crm_sla_policy (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        description TEXT,
        priority VARCHAR(20) DEFAULT 'normal',
        response_target_minutes INTEGER DEFAULT 240,
        resolution_target_minutes INTEGER DEFAULT 2880,
        business_hours JSONB DEFAULT '{}'::jsonb,
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_sla_vendor ON crm_sla_policy(vendor_id);",
    """CREATE TABLE IF NOT EXISTS crm_ticket (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        number VARCHAR(40) NOT NULL,
        subject VARCHAR(255) NOT NULL,
        description TEXT,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        account_id UUID REFERENCES crm_account(id) ON DELETE SET NULL,
        assigned_to UUID REFERENCES "user"(id) ON DELETE SET NULL,
        sla_policy_id UUID REFERENCES crm_sla_policy(id) ON DELETE SET NULL,
        priority VARCHAR(20) DEFAULT 'normal',
        status VARCHAR(30) DEFAULT 'open',
        source VARCHAR(40) DEFAULT 'manual',
        first_response_at TIMESTAMPTZ,
        resolved_at TIMESTAMPTZ,
        closed_at TIMESTAMPTZ,
        sla_breached BOOLEAN DEFAULT FALSE,
        tags JSONB DEFAULT '[]'::jsonb,
        custom_fields JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_ticket_vendor ON crm_ticket(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_ticket_vendor_status ON crm_ticket(vendor_id, status);",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_crm_ticket_number ON crm_ticket(vendor_id, number);",
    "CREATE INDEX IF NOT EXISTS ix_crm_ticket_contact ON crm_ticket(contact_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_ticket_assigned ON crm_ticket(assigned_to);",
    """CREATE TABLE IF NOT EXISTS crm_ticket_comment (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        ticket_id UUID NOT NULL REFERENCES crm_ticket(id) ON DELETE CASCADE,
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        author_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        body TEXT NOT NULL,
        is_internal BOOLEAN DEFAULT FALSE,
        attachments JSONB DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_ticket_comment_ticket ON crm_ticket_comment(ticket_id);",
    """CREATE TABLE IF NOT EXISTS crm_kb_article (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) NOT NULL,
        body TEXT,
        summary TEXT,
        tags JSONB DEFAULT '[]'::jsonb,
        status VARCHAR(20) DEFAULT 'draft',
        view_count INTEGER DEFAULT 0,
        helpful_count INTEGER DEFAULT 0,
        author_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_crm_kb_vendor_slug ON crm_kb_article(vendor_id, slug);",
    "CREATE INDEX IF NOT EXISTS ix_crm_kb_vendor_status ON crm_kb_article(vendor_id, status);",
    # ── Marketing: segments / templates / campaigns / steps / enrollments / events / suppression ──
    """CREATE TABLE IF NOT EXISTS crm_segment (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        description TEXT,
        filter_dsl JSONB DEFAULT '{}'::jsonb,
        contact_count INTEGER DEFAULT 0,
        last_computed_at TIMESTAMPTZ,
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_segment_vendor ON crm_segment(vendor_id);",
    """CREATE TABLE IF NOT EXISTS crm_email_template (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        subject VARCHAR(255) NOT NULL,
        body_html TEXT NOT NULL,
        body_text TEXT,
        merge_tags JSONB DEFAULT '[]'::jsonb,
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_email_template_vendor ON crm_email_template(vendor_id);",
    """CREATE TABLE IF NOT EXISTS crm_campaign (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(255) NOT NULL,
        type VARCHAR(30) NOT NULL DEFAULT 'one_off',
        channel VARCHAR(20) DEFAULT 'email',
        status VARCHAR(20) DEFAULT 'draft',
        template_id UUID REFERENCES crm_email_template(id) ON DELETE SET NULL,
        segment_id UUID REFERENCES crm_segment(id) ON DELETE SET NULL,
        scheduled_at TIMESTAMPTZ,
        started_at TIMESTAMPTZ,
        completed_at TIMESTAMPTZ,
        sent_count INTEGER DEFAULT 0,
        open_count INTEGER DEFAULT 0,
        click_count INTEGER DEFAULT 0,
        bounce_count INTEGER DEFAULT 0,
        unsubscribe_count INTEGER DEFAULT 0,
        settings JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_campaign_vendor ON crm_campaign(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_campaign_vendor_status ON crm_campaign(vendor_id, status);",
    """CREATE TABLE IF NOT EXISTS crm_campaign_step (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        campaign_id UUID NOT NULL REFERENCES crm_campaign(id) ON DELETE CASCADE,
        sort_order INTEGER DEFAULT 0,
        delay_minutes INTEGER DEFAULT 0,
        channel VARCHAR(20) DEFAULT 'email',
        template_id UUID REFERENCES crm_email_template(id) ON DELETE SET NULL,
        condition JSONB DEFAULT '{}'::jsonb,
        action JSONB DEFAULT '{}'::jsonb
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_campaign_step_campaign ON crm_campaign_step(campaign_id);",
    """CREATE TABLE IF NOT EXISTS crm_campaign_enrollment (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        campaign_id UUID NOT NULL REFERENCES crm_campaign(id) ON DELETE CASCADE,
        contact_id UUID NOT NULL REFERENCES crm_contact(id) ON DELETE CASCADE,
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        current_step INTEGER DEFAULT 0,
        status VARCHAR(20) DEFAULT 'active',
        enrolled_at TIMESTAMPTZ DEFAULT now(),
        next_action_at TIMESTAMPTZ,
        last_action_at TIMESTAMPTZ,
        completed_at TIMESTAMPTZ,
        exit_reason VARCHAR(120)
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_enrollment_next ON crm_campaign_enrollment(vendor_id, next_action_at);",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_crm_enrollment_unique ON crm_campaign_enrollment(campaign_id, contact_id);",
    """CREATE TABLE IF NOT EXISTS crm_email_event (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        campaign_id UUID REFERENCES crm_campaign(id) ON DELETE CASCADE,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE CASCADE,
        event VARCHAR(30) NOT NULL,
        target_url VARCHAR(500),
        user_agent VARCHAR(500),
        ip VARCHAR(50),
        occurred_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_email_event_vendor ON crm_email_event(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_email_event_campaign ON crm_email_event(campaign_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_email_event_contact ON crm_email_event(contact_id);",
    """CREATE TABLE IF NOT EXISTS crm_suppression_entry (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        channel VARCHAR(20) NOT NULL,
        address VARCHAR(255) NOT NULL,
        reason VARCHAR(120),
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_crm_suppression_unique ON crm_suppression_entry(vendor_id, channel, address);",
    # ── Workflows ────────────────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_workflow (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        trigger JSONB DEFAULT '{}'::jsonb,
        steps JSONB DEFAULT '[]'::jsonb,
        status VARCHAR(20) DEFAULT 'active',
        requires_approval BOOLEAN DEFAULT FALSE,
        last_run_at TIMESTAMPTZ,
        run_count INTEGER DEFAULT 0,
        success_count INTEGER DEFAULT 0,
        failure_count INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_workflow_vendor ON crm_workflow(vendor_id);",
    """CREATE TABLE IF NOT EXISTS crm_workflow_run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        workflow_id UUID NOT NULL REFERENCES crm_workflow(id) ON DELETE CASCADE,
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        entity_type VARCHAR(40),
        entity_id UUID,
        status VARCHAR(20) DEFAULT 'running',
        log JSONB DEFAULT '[]'::jsonb,
        error TEXT,
        approved_by UUID REFERENCES "user"(id) ON DELETE SET NULL,
        approved_at TIMESTAMPTZ,
        started_at TIMESTAMPTZ DEFAULT now(),
        finished_at TIMESTAMPTZ
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_workflow_run_workflow ON crm_workflow_run(workflow_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_workflow_run_vendor ON crm_workflow_run(vendor_id);",
    # ── Integrations / audit ─────────────────────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_integration (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        provider VARCHAR(40) NOT NULL,
        label VARCHAR(120),
        status VARCHAR(20) DEFAULT 'connected',
        encrypted_credentials TEXT,
        settings JSONB DEFAULT '{}'::jsonb,
        last_synced_at TIMESTAMPTZ,
        last_error TEXT,
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_crm_integration_vendor_provider ON crm_integration(vendor_id, provider);",
    """CREATE TABLE IF NOT EXISTS crm_audit_log (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        actor_id UUID REFERENCES "user"(id) ON DELETE SET NULL,
        actor_type VARCHAR(20) DEFAULT 'user',
        entity VARCHAR(60) NOT NULL,
        entity_id UUID,
        action VARCHAR(40) NOT NULL,
        before JSONB,
        after JSONB,
        ip VARCHAR(50),
        user_agent VARCHAR(500),
        request_path VARCHAR(500),
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_audit_vendor_created ON crm_audit_log(vendor_id, created_at);",
    "CREATE INDEX IF NOT EXISTS ix_crm_audit_entity ON crm_audit_log(entity, entity_id);",
    # ── AI / chat / journey / intake tokens ──────────────────────────
    """CREATE TABLE IF NOT EXISTS crm_ai_insight (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        entity_type VARCHAR(40) NOT NULL,
        entity_id UUID NOT NULL,
        kind VARCHAR(40) NOT NULL,
        content JSONB DEFAULT '{}'::jsonb,
        model VARCHAR(80),
        confidence NUMERIC(5,2),
        generated_at TIMESTAMPTZ DEFAULT now(),
        expires_at TIMESTAMPTZ
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_ai_entity ON crm_ai_insight(entity_type, entity_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_ai_vendor_kind ON crm_ai_insight(vendor_id, kind);",
    """CREATE TABLE IF NOT EXISTS crm_chat_conversation (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        customer_id UUID REFERENCES customer(id) ON DELETE SET NULL,
        visitor_id VARCHAR(120),
        visitor_name VARCHAR(120),
        visitor_email VARCHAR(255),
        channel VARCHAR(20) DEFAULT 'widget',
        status VARCHAR(20) DEFAULT 'open',
        assigned_to UUID REFERENCES "user"(id) ON DELETE SET NULL,
        bot_handled BOOLEAN DEFAULT TRUE,
        last_message_at TIMESTAMPTZ DEFAULT now(),
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_chat_conv_vendor ON crm_chat_conversation(vendor_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_chat_conv_vendor_status ON crm_chat_conversation(vendor_id, status);",
    "CREATE INDEX IF NOT EXISTS ix_crm_chat_conv_visitor ON crm_chat_conversation(vendor_id, visitor_id);",
    """CREATE TABLE IF NOT EXISTS crm_chat_message (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        conversation_id UUID NOT NULL REFERENCES crm_chat_conversation(id) ON DELETE CASCADE,
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        sender VARCHAR(20) NOT NULL,
        sender_id UUID,
        body TEXT,
        attachments JSONB DEFAULT '[]'::jsonb,
        metadata JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_chat_msg_conv ON crm_chat_message(conversation_id);",
    """CREATE TABLE IF NOT EXISTS crm_journey_event (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        contact_id UUID REFERENCES crm_contact(id) ON DELETE SET NULL,
        customer_id UUID REFERENCES customer(id) ON DELETE SET NULL,
        visitor_id VARCHAR(120),
        event_type VARCHAR(60) NOT NULL,
        payload JSONB DEFAULT '{}'::jsonb,
        occurred_at TIMESTAMPTZ DEFAULT now()
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_journey_vendor_time ON crm_journey_event(vendor_id, occurred_at);",
    "CREATE INDEX IF NOT EXISTS ix_crm_journey_contact ON crm_journey_event(contact_id);",
    "CREATE INDEX IF NOT EXISTS ix_crm_journey_visitor ON crm_journey_event(vendor_id, visitor_id);",
    """CREATE TABLE IF NOT EXISTS crm_lead_intake_token (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vendor_id UUID NOT NULL REFERENCES vendor(id) ON DELETE CASCADE,
        token VARCHAR(64) NOT NULL UNIQUE,
        label VARCHAR(120),
        source_default VARCHAR(80) DEFAULT 'form',
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT now(),
        last_used_at TIMESTAMPTZ
    );""",
    "CREATE INDEX IF NOT EXISTS ix_crm_intake_token ON crm_lead_intake_token(token);",
    "CREATE INDEX IF NOT EXISTS ix_crm_intake_vendor ON crm_lead_intake_token(vendor_id);",
]


# Tables in dependency order so children drop before parents.
DROP_TABLES: list[str] = [
    "crm_lead_intake_token",
    "crm_journey_event",
    "crm_chat_message",
    "crm_chat_conversation",
    "crm_ai_insight",
    "crm_audit_log",
    "crm_integration",
    "crm_workflow_run",
    "crm_workflow",
    "crm_suppression_entry",
    "crm_email_event",
    "crm_campaign_enrollment",
    "crm_campaign_step",
    "crm_campaign",
    "crm_email_template",
    "crm_segment",
    "crm_kb_article",
    "crm_ticket_comment",
    "crm_ticket",
    "crm_sla_policy",
    "crm_call_recording",
    "crm_communication_log",
    "crm_activity",
    "crm_lead",
    "crm_deal",
    "crm_stage",
    "crm_pipeline",
    "crm_contact",
    "crm_account",
]


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # CRM module is Postgres-only (uses JSONB, gen_random_uuid()).
        return
    for stmt in DDL_STATEMENTS:
        op.execute(stmt)


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for table in DROP_TABLES:
        op.execute(f'DROP TABLE IF EXISTS {table} CASCADE;')
