"""hr_full_modules — recruitment, onboarding, performance, compliance, training, ESS

Revision ID: e1f2a3b4c5d6
Revises: d1e2f3a4b5c6
Create Date: 2026-04-18 21:00:00.000000
"""
from typing import Sequence, Union
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'e1f2a3b4c5d6'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ─────────────── Recruitment & Onboarding ───────────────
    op.create_table('hr_job_posting',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('department_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_department.id', ondelete='SET NULL')),
        sa.Column('designation_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_designation.id', ondelete='SET NULL')),
        sa.Column('store_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('store.id', ondelete='SET NULL')),
        sa.Column('employment_type', sa.String(20), server_default='full_time'),
        sa.Column('location', sa.String(200)),
        sa.Column('openings', sa.Integer(), server_default='1'),
        sa.Column('salary_min', sa.Numeric(12, 2)),
        sa.Column('salary_max', sa.Numeric(12, 2)),
        sa.Column('description', sa.Text()),
        sa.Column('requirements', sa.Text()),
        sa.Column('benefits', sa.Text()),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('public_slug', sa.String(120), unique=True),
        sa.Column('posted_at', sa.DateTime(timezone=True)),
        sa.Column('closes_at', sa.DateTime(timezone=True)),
        sa.Column('posted_by', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_job_vendor_status', 'hr_job_posting', ['vendor_id', 'status'])

    op.create_table('hr_candidate',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('full_name', sa.String(200), nullable=False),
        sa.Column('email', sa.String(255)),
        sa.Column('phone', sa.String(30)),
        sa.Column('resume_url', sa.String(500)),
        sa.Column('current_company', sa.String(200)),
        sa.Column('current_designation', sa.String(150)),
        sa.Column('total_experience_years', sa.Numeric(4, 1)),
        sa.Column('current_ctc', sa.Numeric(14, 2)),
        sa.Column('expected_ctc', sa.Numeric(14, 2)),
        sa.Column('notice_period_days', sa.Integer()),
        sa.Column('location', sa.String(200)),
        sa.Column('source', sa.String(40)),
        sa.Column('skills', postgresql.JSONB(), server_default='[]'),
        sa.Column('tags', postgresql.JSONB(), server_default='[]'),
        sa.Column('notes', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_candidate_vendor_email', 'hr_candidate', ['vendor_id', 'email'])

    op.create_table('hr_job_application',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('candidate_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_candidate.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('job_posting_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_job_posting.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('current_stage', sa.String(30), server_default='applied'),
        sa.Column('rating', sa.Integer()),
        sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('rejection_reason', sa.Text()),
        sa.Column('cover_letter', sa.Text()),
        sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('candidate_id', 'job_posting_id', name='uq_application_candidate_job'),
    )
    op.create_index('ix_hr_application_vendor_stage', 'hr_job_application', ['vendor_id', 'current_stage'])

    op.create_table('hr_interview_round',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('application_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_job_application.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('round_number', sa.Integer(), server_default='1'),
        sa.Column('round_name', sa.String(100)),
        sa.Column('scheduled_at', sa.DateTime(timezone=True)),
        sa.Column('duration_min', sa.Integer(), server_default='45'),
        sa.Column('mode', sa.String(20), server_default='video'),
        sa.Column('location_or_link', sa.String(500)),
        sa.Column('interviewer_user_ids', postgresql.JSONB(), server_default='[]'),
        sa.Column('status', sa.String(20), server_default='scheduled'),
        sa.Column('rating', sa.Integer()),
        sa.Column('feedback', sa.Text()),
        sa.Column('recommendation', sa.String(20)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_interview_vendor_when', 'hr_interview_round', ['vendor_id', 'scheduled_at'])

    op.create_table('hr_onboarding_template',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('description', sa.String(400)),
        sa.Column('designation_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_designation.id', ondelete='SET NULL')),
        sa.Column('department_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_department.id', ondelete='SET NULL')),
        sa.Column('is_default', sa.Boolean(), server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_onboarding_template_item',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_onboarding_template.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('sequence', sa.Integer(), server_default='0'),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('category', sa.String(40), server_default='general'),
        sa.Column('default_due_offset_days', sa.Integer(), server_default='7'),
        sa.Column('default_assignee_role', sa.String(40)),
    )

    op.create_table('hr_onboarding_checklist',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_onboarding_template.id', ondelete='SET NULL')),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('target_completion_date', sa.Date()),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(20), server_default='in_progress'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_onboarding_task',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('checklist_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_onboarding_checklist.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('sequence', sa.Integer(), server_default='0'),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('category', sa.String(40), server_default='general'),
        sa.Column('due_date', sa.Date()),
        sa.Column('assignee_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('status', sa.String(20), server_default='pending'),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('notes', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ─────────────── Performance ───────────────
    op.create_table('hr_review_cycle',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('period_start', sa.Date(), nullable=False),
        sa.Column('period_end', sa.Date(), nullable=False),
        sa.Column('review_type', sa.String(30), server_default='annual'),
        sa.Column('rating_scale_max', sa.Integer(), server_default='5'),
        sa.Column('self_review_required', sa.Boolean(), server_default=sa.true()),
        sa.Column('manager_review_required', sa.Boolean(), server_default=sa.true()),
        sa.Column('peer_review_count', sa.Integer(), server_default='0'),
        sa.Column('enable_kpi_scoring', sa.Boolean(), server_default=sa.true()),
        sa.Column('kpi_template', postgresql.JSONB(), server_default='[]'),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('launched_at', sa.DateTime(timezone=True)),
        sa.Column('closes_at', sa.DateTime(timezone=True)),
        sa.Column('closed_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_performance_goal',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('cycle_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_review_cycle.id', ondelete='SET NULL')),
        sa.Column('parent_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_performance_goal.id', ondelete='SET NULL')),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('category', sa.String(40)),
        sa.Column('target_value', sa.String(100)),
        sa.Column('weight', sa.Numeric(5, 2), server_default='10'),
        sa.Column('progress_pct', sa.Integer(), server_default='0'),
        sa.Column('start_date', sa.Date()),
        sa.Column('target_date', sa.Date()),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_performance_review',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('cycle_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_review_cycle.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('reviewer_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('status', sa.String(30), server_default='draft'),
        sa.Column('self_assessment', sa.Text()),
        sa.Column('self_rating', sa.Numeric(3, 2)),
        sa.Column('self_submitted_at', sa.DateTime(timezone=True)),
        sa.Column('manager_comments', sa.Text()),
        sa.Column('overall_rating', sa.Numeric(3, 2)),
        sa.Column('strengths', sa.Text()),
        sa.Column('improvement_areas', sa.Text()),
        sa.Column('promotion_recommended', sa.Boolean(), server_default=sa.false()),
        sa.Column('salary_change_suggestion_pct', sa.Numeric(5, 2)),
        sa.Column('manager_submitted_at', sa.DateTime(timezone=True)),
        sa.Column('employee_acknowledgement', sa.Text()),
        sa.Column('acknowledged_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('cycle_id', 'employee_id', name='uq_review_cycle_emp'),
    )
    op.create_index('ix_hr_review_vendor_status', 'hr_performance_review', ['vendor_id', 'status'])

    op.create_table('hr_review_kpi_score',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('review_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_performance_review.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('kpi_key', sa.String(60), nullable=False),
        sa.Column('label', sa.String(150)),
        sa.Column('weight', sa.Numeric(5, 2), server_default='10'),
        sa.Column('self_score', sa.Numeric(3, 2)),
        sa.Column('manager_score', sa.Numeric(3, 2)),
        sa.Column('comments', sa.Text()),
    )

    op.create_table('hr_feedback',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('from_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('to_employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('feedback_type', sa.String(20), server_default='praise'),
        sa.Column('visibility', sa.String(20), server_default='private'),
        sa.Column('title', sa.String(200)),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('related_competency', sa.String(100)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ─────────────── Compliance ───────────────
    op.create_table('hr_policy',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('category', sa.String(60)),
        sa.Column('summary', sa.Text()),
        sa.Column('body', sa.Text()),
        sa.Column('version', sa.Integer(), server_default='1'),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('effective_from', sa.Date()),
        sa.Column('expires_on', sa.Date()),
        sa.Column('requires_acknowledgement', sa.Boolean(), server_default=sa.true()),
        sa.Column('audience', sa.String(40), server_default='all'),
        sa.Column('audience_filter', postgresql.JSONB(), server_default='{}'),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('published_at', sa.DateTime(timezone=True)),
        sa.Column('published_by', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_policy_vendor_status', 'hr_policy', ['vendor_id', 'status'])

    op.create_table('hr_policy_acknowledgement',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('policy_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_policy.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('policy_version', sa.Integer(), server_default='1'),
        sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('notes', sa.Text()),
        sa.UniqueConstraint('policy_id', 'employee_id', 'policy_version', name='uq_policy_ack_emp_version'),
    )

    op.create_table('hr_compliance_certification',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('type', sa.String(40)),
        sa.Column('issued_by', sa.String(200)),
        sa.Column('cert_number', sa.String(100)),
        sa.Column('issued_on', sa.Date()),
        sa.Column('expires_on', sa.Date()),
        sa.Column('document_url', sa.String(500)),
        sa.Column('notes', sa.Text()),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_cert_vendor_expiry', 'hr_compliance_certification', ['vendor_id', 'expires_on'])

    op.create_table('hr_compliance_audit_log',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('actor_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('actor_label', sa.String(200)),
        sa.Column('action', sa.String(60), nullable=False),
        sa.Column('entity_type', sa.String(60), nullable=False),
        sa.Column('entity_id', postgresql.UUID(as_uuid=True)),
        sa.Column('summary', sa.String(400)),
        sa.Column('diff', postgresql.JSONB(), server_default='{}'),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_audit_vendor_when', 'hr_compliance_audit_log', ['vendor_id', 'created_at'])
    op.create_index('ix_hr_audit_entity', 'hr_compliance_audit_log', ['entity_type', 'entity_id'])

    # ─────────────── Training ───────────────
    op.create_table('hr_training_program',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('category', sa.String(60)),
        sa.Column('cover_image_url', sa.String(500)),
        sa.Column('is_mandatory', sa.Boolean(), server_default=sa.false()),
        sa.Column('target_audience', sa.String(40), server_default='all'),
        sa.Column('audience_filter', postgresql.JSONB(), server_default='{}'),
        sa.Column('estimated_hours', sa.Numeric(5, 2)),
        sa.Column('issues_certificate', sa.Boolean(), server_default=sa.true()),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_training_course',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('program_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_program.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('sequence', sa.Integer(), server_default='0'),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('content_type', sa.String(20), server_default='text'),
        sa.Column('content_url', sa.String(500)),
        sa.Column('body_html', sa.Text()),
        sa.Column('duration_min', sa.Integer()),
        sa.Column('pass_score_pct', sa.Integer(), server_default='70'),
        sa.Column('is_required', sa.Boolean(), server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('hr_quiz_question',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('course_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_course.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('sequence', sa.Integer(), server_default='0'),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('question_type', sa.String(20), server_default='single'),
        sa.Column('options', postgresql.JSONB(), server_default='[]'),
        sa.Column('explanation', sa.Text()),
        sa.Column('points', sa.Integer(), server_default='1'),
    )

    op.create_table('hr_training_enrollment',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('program_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_program.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('due_date', sa.Date()),
        sa.Column('status', sa.String(20), server_default='enrolled'),
        sa.Column('progress_pct', sa.Integer(), server_default='0'),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('certificate_url', sa.String(500)),
        sa.UniqueConstraint('program_id', 'employee_id', name='uq_enroll_program_emp'),
    )

    op.create_table('hr_course_completion',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('enrollment_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_enrollment.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('course_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_course.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('score_pct', sa.Integer()),
        sa.Column('passed', sa.Boolean(), server_default=sa.false()),
        sa.Column('answers', postgresql.JSONB(), server_default='{}'),
        sa.Column('attempts', sa.Integer(), server_default='1'),
        sa.UniqueConstraint('enrollment_id', 'course_id', name='uq_completion_enroll_course'),
    )

    op.create_table('hr_training_certificate',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('enrollment_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_training_enrollment.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('certificate_number', sa.String(60), unique=True),
        sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('valid_until', sa.Date()),
        sa.Column('title_snapshot', sa.String(200)),
        sa.Column('employee_name_snapshot', sa.String(200)),
        sa.Column('download_html', sa.Text()),
    )

    # ─────────────── ESS ───────────────
    op.create_table('hr_announcement',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('category', sa.String(40), server_default='general'),
        sa.Column('audience', sa.String(40), server_default='all'),
        sa.Column('audience_filter', postgresql.JSONB(), server_default='{}'),
        sa.Column('pinned', sa.Boolean(), server_default=sa.false()),
        sa.Column('cover_image_url', sa.String(500)),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('publish_at', sa.DateTime(timezone=True)),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('published_by', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_announce_vendor_status', 'hr_announcement', ['vendor_id', 'status'])

    op.create_table('hr_announcement_read',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('announcement_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_announcement.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('announcement_id', 'employee_id', name='uq_announce_read_emp'),
    )

    op.create_table('hr_expense_claim',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('claim_number', sa.String(40), unique=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('category', sa.String(40)),
        sa.Column('expense_date', sa.Date()),
        sa.Column('currency', sa.String(8), server_default='INR'),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('receipts', postgresql.JSONB(), server_default='[]'),
        sa.Column('status', sa.String(20), server_default='draft'),
        sa.Column('submitted_at', sa.DateTime(timezone=True)),
        sa.Column('approver_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('decided_at', sa.DateTime(timezone=True)),
        sa.Column('decision_note', sa.Text()),
        sa.Column('paid_at', sa.DateTime(timezone=True)),
        sa.Column('payment_reference', sa.String(100)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_expense_vendor_status', 'hr_expense_claim', ['vendor_id', 'status'])

    op.create_table('hr_helpdesk_ticket',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('vendor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('employee_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_employee_profile.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('ticket_number', sa.String(40), unique=True),
        sa.Column('category', sa.String(40), server_default='hr'),
        sa.Column('subject', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('priority', sa.String(20), server_default='normal'),
        sa.Column('status', sa.String(20), server_default='open'),
        sa.Column('assignee_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('sla_due_at', sa.DateTime(timezone=True)),
        sa.Column('resolved_at', sa.DateTime(timezone=True)),
        sa.Column('closed_at', sa.DateTime(timezone=True)),
        sa.Column('is_anonymous', sa.Boolean(), server_default=sa.false()),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('ix_hr_ticket_vendor_status', 'hr_helpdesk_ticket', ['vendor_id', 'status'])

    op.create_table('hr_helpdesk_ticket_comment',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('ticket_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('hr_helpdesk_ticket.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('author_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('vendor_user.id', ondelete='SET NULL')),
        sa.Column('is_staff_reply', sa.Boolean(), server_default=sa.false()),
        sa.Column('is_internal', sa.Boolean(), server_default=sa.false()),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for tbl in [
        'hr_helpdesk_ticket_comment', 'hr_helpdesk_ticket',
        'hr_expense_claim',
        'hr_announcement_read', 'hr_announcement',
        'hr_training_certificate', 'hr_course_completion', 'hr_training_enrollment',
        'hr_quiz_question', 'hr_training_course', 'hr_training_program',
        'hr_compliance_audit_log', 'hr_compliance_certification',
        'hr_policy_acknowledgement', 'hr_policy',
        'hr_feedback', 'hr_review_kpi_score', 'hr_performance_review',
        'hr_performance_goal', 'hr_review_cycle',
        'hr_onboarding_task', 'hr_onboarding_checklist',
        'hr_onboarding_template_item', 'hr_onboarding_template',
        'hr_interview_round', 'hr_job_application', 'hr_candidate', 'hr_job_posting',
    ]:
        op.execute(f'DROP TABLE IF EXISTS {tbl} CASCADE')
